### ISSUE TITLE
Static export has no doctype

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#102]
This causes IE to render the page in quirks mode and breaks the layout. On the online site this has a doctype as follows: &lt;!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

We need this on the static export as well. Thank you.

**Comment by orangedrink** [comment]
Just a heads up that I'm scheduled to produce a flash drive using this on Thursday.

**Comment by daviddurand** [comment]
Now generating an HTML4 strict header.

**Comment by orangedrink** [comment]
Was working for a little bit but now we're back to just "&lt;html>"

**Comment by daviddurand** [comment]
Sorry about this -- I had made an immediate patch, but the version control archive was a little behind. It is back now, and the change is properly in place in the archive as well.

**Comment by orangedrink** [comment]
OK thank you.
