### ISSUE TITLE
ASPPA site has no controls when documents appear in full screen mode

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#103]
To reproduce visit http://s64705085-preview.tizrapublisher.com/erisa-outline-book-chapter-1a/1 and click the full screen button

Let me know if you have any questions.

**Comment by orangedrink** [comment]
#99

**Comment by daviddurand** [comment]
This is a duplicate of #99, and also seems to be fixed at this point.
