### ISSUE TITLE
Online help and support link not working on static export

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#104]
Online the link goes to http://omniplayground.tizrapublisher.com/~contactUs but on the static export it comes out as "#"

We use a wufoo form on this page so our version of that layout should work on a static export (assuming internet connectivity). Any chance of making this link and page work for us?

**Comment by orangedrink** [comment]
Could we make the %URL_CONTACT_US% macro resolve to the full online url even on the static export?

**Comment by daviddurand** [comment]
The original plan was that online-only features would not work, and that you would use either variant designs or style sheets to splice out problems.

That said, we could make an exception for this. It's not clear to me that a link to the website would be better than, say, an email: URL for the site contact address -- which is more likely to last, and perhaps not to fail the same way in offline reading.

I'll try to put link back to the original site in place, but I can't guarantee it for tomorrow right now -- could you alter the export design for your Thursday deadline. I will try to look at it later in the day, and will let you know if I can get something done.

**Comment by orangedrink** [comment]
Thanks David. We can definitely do without this for the short term.

**Comment by daviddurand** [comment]
fixed. fix should be live.
