### ISSUE TITLE
Virtual collections not working with keyword lists

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#106]
I'm using the virtual collections on the WEF site the same way I am for TRB's subject listings but instead of seeing the VC I'm redirected to the home page

http://weftec2012.tizrapublisher.com/top@subject=test

Let me know if I'm doing something wrong.

**Comment by daviddurand** [comment]
It looks like the metatype of the collection was not set to `Book`. You need to pick a type for virtual collections and all their contents have to be of that exact type.

I did also republish the book that's a member of the `test` instance, but checking tags with my test collection indicated that you had already done that.

In the future, 'll try to look into making sure that VCs check for more things that _might_ be a problem, but they are definitely power tools, and they are definitely a bit on the model of "you asked for it; you got it".

**Comment by orangedrink** [comment]
That's how I like my tools. It just makes for a bit of a learning curve. 

Thanks David!
