### ISSUE TITLE
Unable to edit Omniplayground

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#108]
http://omniplayground.tizrapublisher.com/
https://secure.agilepdf.com/admin/10fg0d/main

I can not edit any of the layouts or save a design without getting an error message. 
I'm trying to put together a customer sample for a visit on Wednesday and I was going to use our playground site to do so.

Last thing I was doing before I started getting the error was copying some text out of a master block in the "user personalization" layout. After I got the text, I put everything in the trash because nothing needed to get updated. 

I'm guessing I must have done something the system didn't like because this issue is currently only showing up on this site.

**Comment by ghost** [comment]
This seems to be resolved now... If there was anything that I did that caused this, please let me know. Thanks.

**Comment by daviddurand** [comment]
Sorry for the delay in responding. Some of the performance changes from Friday have been causing this intermittent editing problem -- the database is getting confused when blocks are deleted. The problem resolves itself spontaneously when database cache expires. It's a sporadic problem which makes the testing a bit difficult, but I will be updating the system tonight.

**Comment by ghost** [comment]
Thanks for the update. I was worried that I was doing something wrong.

**Comment by daviddurand** [comment]
Let me know if it keeps happening. Should be better now.

**Comment by ghost** [comment]
Will do. Thanks.
