### ISSUE TITLE
Can't Publish Images

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#113]
nobcche51538.tizrapublisher.com 

After adding a new image, it won't publish. 
If you leave the images area and then return, you can't open any of the images.

This site is suppose to proof today.

Please let us know if there is anything that we have done to create this problem or if this is a bug.

**Comment by daviddurand** [comment]
I found and fixed this problem. Publishing of images was actually working properly from the list view, as I was able to tell from using the image block -- but the editor was not showing up due to some javascript issues.

Sorry I did not get to look at this on Friday.
