### ISSUE TITLE
Document Filter Bug

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#114]
when the filtered keyword includes an & in it, the filter seems to truncate the text at the ampersand and then returns nothing when filtered because the keyword doesn't match the truncated filter.

Example: 
A filter List of "Session: Alternative Energy & Environmental Chemistry"
becomes
"Session:Alternative Energy" after clicking "Filter"

**Comment by daviddurand** [comment]
This is a URL escaping and web parameter issue -- perhaps with some javascript interactions.  Will get to it, but hope you can work around it for a while.

**Comment by ghost** [comment]
I worked around the problem, just figured I would let you know about it.

**Comment by daviddurand** [comment]
This is fixed. You may need to force refresh or purge your cache to be sure you get the new javascript.
