### ISSUE TITLE
URGENT All Tizra sites are down

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#120]
http://omniplayground.tizrapublisher.com/
http://amonline.trb.org/
http://handouts.sde.com/

And all the others I checked are down. Please fix ASAP! 

Thanks.

**Comment by daviddurand** [comment]
There was a system monitoring failure. We have made changes to our backup monitors and are still evaluating and improving the setup to prevent this problem from recurring.
