### ISSUE TITLE
Sorting Collections by Title Bug

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#121]
http://knowledgecenter.clemetrobar.org/2ham98/

The above link is a link to a static page I created that has a "List Block" showing any "Collection" with the tag of "event". This list block has a sort by "Title", Ascending.

The resulting order isn't in any kind of noticeable order, but I would like it in an alpha order. 

I have unpublished and republished all of the collections and static pages that are involved with this page.

**Comment by ghost** [comment]
I'm thinking this is less of a bug and more of missing metadata. 
It seems as if the list block doesn't list "Name", which is the equivalent of the documents "Title" for collections. 

Is there any way to fix the list block so we don't have to add a second metadata field to each collection just to sort by the name of the collections?

If any of the above doesn't make sense, let me know.

**Comment by daviddurand** [comment]
As you already figured out (as I wrote this), this is a consequence of an early design decision that has been hard to reverse: Collections don't have "Titles", but rather they have "Names" which are not the same thing, and are not even stored in the same way.

As lists of collections and collections of collections have become more important, this is more of a problem. I will look into what kind of fix makes sense. I think the simplest tack will be to change the indexing, but I will look for a way to transition to a more uniform model altogether.

**Comment by ghost** [comment]
Thank you David.
For a temporary fix I'm going to setup another metadata field for title in the collections, but this site is setup to manage all of the events for a year and the extra work may become an issue eventually for our customer.

Please let me know if you are able to come up with anything and then I will fix the list block to work with your fix.

**Comment by daviddurand** [comment]
The "Name" field was already being indexed. I've changed the Metatype definitions, but the database caches are hiding the change for now. You should see it as a sorting option tomorrow.

**Comment by ghost** [comment]
Glad to hear. Thanks for looking into this for us.
