### ISSUE TITLE
creating excerpts when logical page number is ON

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#122]
When I have Logical Page Numbering turned ON, I go to create an excerpt from the Document's TOC.

In the TOC, the file page = 272 and the Doc page = 252

I click Create Excerpt.

The excerpt is created for page range 252- 291

In the Tizra reader, the page number for the start of the excerpt is 232. as is the printed page number.

There are 20 pages of front matter in of roman numerals for the document i'm making excerpts for. 

Document = http://cbw.tizrapublisher.com/2li0fg/

Excerpt = http://cbw.tizrapublisher.com/2lie7o/2li0fg/252

**Comment by daviddurand** [comment]
This has the same underlying cause as #117
