### ISSUE TITLE
PDF full screen problem

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#123]
In full screen mode pages are over the controls and look very small. To reproduce clcik the full screen link on this page http://omniplayground.tizrapublisher.com/000445_Handout/1

You can also reproduce on your own demo site

http://demo.tizra.com/lu47g/21 and click zoom to full screen.

**Comment by daviddurand** [comment]
Thanks for the report.

This was a problem with PDF mode display only -- something that we are moving away from as we make sure that we've really solved the last few problems with image display.

I got a fix in place, but of course for many people the zoom buttons are still broken in the zoom reader as changing the size of the PDF plugin does not change the size of the PDF in Chrome and Safari.
