### ISSUE TITLE
IE7 Compatablity mode not available

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#126]
http://fafp2012su.conferencespot.org/ looks bad in IE because of the lack of the IE7 compatability mode  meta tag but I'm unable to turn in back on. 

Please expose this setting on this and any of our other older sites. Thank you.

**Comment by orangedrink** [comment]
Until you do this several of our sites are broken. Please hurry.

**Comment by adane** [comment]
IE7 is something like 3% of traffic vs. 19% for IE9.  We'll see what we can do but it seems like solving the IE9 problems was a higher priority.

**Comment by orangedrink** [comment]
OK. It's broken in IE9 and (presumably) works in IE 7. Please hurry. Thanks Abe.

**Comment by adane** [comment]
David is working on this now.

**Comment by adane** [comment]
There's now a property to turn the IE7 compatibility on and off for all sites.  Note: It looks like some of your designs include the meta tag, so you'll need to make sure the tag is set as you want it there as well.

**Comment by daviddurand** [comment]
Just as a note, the IE7 tag was included twice in the global header on that site by the design. I don't know what that would do, but perhaps in IE, two compatibility tags produce some kind of error and cancel each other out?

What I remember from Ryan was the original request to make the IE7 tag optional, as it screwed up sites rendered in IE9, so perhaps the tag's _presence_ is the cause of the actual rendering problem, and the duplicate occurrence messed up your testing.

In any case, the option is available for all sites now, so you should remove the tag from any designs, and control it with the site property from now on.

**Comment by orangedrink** [comment]
That was included in my attempts to make the site work before you had turned on the setting. That wasn't working because the compatibility metatag has to come before any other elements in the head with the exception of the title and other meta tags.
