### ISSUE TITLE
Macro Bug

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#129]
%TAG_VALUE_OBJECT(stateapprovals,Not Available)%

When I use the above for http://knowledgecenter.appraisalinstitute.org/instructor-litigation-skills-for-the-appraiser/ "Not Available" doesn't show up when there isn't anything in stateapprovals metadata.

Am I using the macro correctly? I was under the impression that anything after the comma would show up when the metadata field was empty.

Thanks.

**Comment by daviddurand** [comment]
Yes, this is a bug. Most people have used the `METADATA_EXISTS` option of `%IF_CONTEXT_VALUE_BEGIN(`

I've fixed it, but you won't see the update in place until tomorrow.

**Comment by ghost** [comment]
Sounds good. Thanks.
