### ISSUE TITLE
Relative URLs on ToC Break When ToC is Accessed From Purchase Receipt

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#131]
Steps to reproduce...

1) Start at this document ToC...

http://wfu.tizrapublisher.com/2kppdj/

2) Add free offer to cart and complete checkout, which takes you to a receipt page...

https://secure.agilepdf.com/commerce/25dcgg/fulfiller_free

3) Click on link to purchased item, which takes you to the ToC, with this URL...

http://wfu.tizrapublisher.com/2kppdj?__utma=1.284023568.1296680370.1350049538.1350051787.421&__utmb=1.8.10.1350051787&__utmc=1&__utmx=-&__utmz=1.1350051787.421.19.utmcsr=wfu.tizrapublisher.com|utmccn=(referral)|utmcmd=referral|utmcct=/cart&__utmv=-&__utmk=220079513

Image and link referencing attachment are broken...it looks like because t he document component of the URL isn't in the path.

**Comment by daviddurand** [comment]
fixed trailing slash on URLs in receipts.
