### ISSUE TITLE
Purchasing Bug :: Needs Help ASAP

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#133]
http://library.smrp.org/full_metrics/

I setup an offer for SMRP on the above document. I have heard that the process goes through to the final step and then an error comes up and the purchase doesn't complete.

To test this out, I created a temporary offer only visible to the account set omnipress and put myself into it. Went through the purchase and hit the error.

I need to know if we have set something up incorrectly, or if this is a bug in the system as soon as possible because this customer is currently at an event promoting the site and this discounted offer.

Thanks, Ryan

**Comment by adane** [comment]
We'll have a look.  I did see that there were a number of successful purchases on SMRP around 11am.

**Comment by daviddurand** [comment]
What error are you getting? are you doing it on the test or live site?

## what offer should we be looking at?

David G. Durand
CEO / CTO
Tizra
9 Catalpa Road
Providence, RI 02906

Email: david.durand@tizra.com
Phone: +1 401 935-5317
FAX: +1 401 273-5171
Web: http://www.tizra.com/
Blog: http://blog.tizra.com/

Online publishing unbound.

**Comment by adane** [comment]
It looks like another order just successfully went through on SMRP in the past minute or so.  Order confirmation email below...

Subject:    Your SMRP Knowledge Center purchase
Date:   October 18, 2012 4:24:35 PM EDT
Thank you for purchasing online publications from SMRP Knowledge Center. Details are below.

Purchase of SMRP Guide to Maintenance Work Sampling for $ 25.00
Access Term: 60 days upon first access 
View purchased content: http://library.smrp.org/work_sampling
Card transaction details: VISA: ************2617.

A username and password are required for access to the site. Your username is brian.pritchard@shell.com. If you forget your password, you can reset it at:

http://library.smrp.org/~passwordHelp

To see a complete list of your online purchases, and manage your account information, go to...

http://library.smrp.org/view/ruj24/~userInfo

Please bookmark these pages and save this email so you can easily find your online purchases in the future.

If you have any questions or encounter problems, please do not hesitate to contact us at enduser-support@tizra.com

Fine Print transaction details. Include in case of problems. Credit card Transaction ID: 4Y125138NT832520X||29314099-1350591871098-239125116 Tizra Transaction ID: 91854111

**Comment by daviddurand** [comment]
It looks like we solved this by email while github was napping. The commerce log field was too short for the name of the really long offer:

email snip:

"Limited Time Offer--Purchase SMRP Best Practices 3rd Edition and get Full Access to Metrics Online (Includes Metrics, Harmonized Metrics, Guidelines, and The Glossary) for $470. Note: 4th Edition estimated publication is Spring/Summer 2013. Pricing will increase for the PDF and Metrics Online will not be included. Upgrades will not apply to the 4th edition. However, with Metrics Online you will get all the newly updated metrics to be included in the 4th edition as they are published online--many before the 4th edition is published."

Abe, with the fact that purchases are going through, do you think there could be a problem with the length of the name of the offer? This is the only thing that would make sense if some purchase are going through and this one isn't. I have no problem adjusting the name, I just put in what the customer asked for and didn't think that the length of the name would have an impact on the purchase going through.
