### ISSUE TITLE
URGENT All Tizra sites are down

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#134]
When trying to load any tizra site I see this error in chrome

http://screencast.com/t/IYwR07owW

**Comment by daviddurand** [comment]
Amazon is having a data center problem which was taking one of our disks offline.

We are now running from a backup as of midnight last night, so it would be good not to make updates in the admin area until we are running from the correctly restored final state. We are now dependent on Amazon to get our disk back online so we can get back to normal operation.

**Comment by orangedrink** [comment]
Thanks David. Let me know when these sites are back to normal.

**Comment by daviddurand** [comment]
notifications went out the mailing list this morning. Sorry for the problems.
