### ISSUE TITLE
Pakistan is not available as a country in credit card detail screen..

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#135]
I received this in an email:

"Thanks Dave the link is working and taking me to the purchasing option, but there is another problem in credit card detail form my country name (Pakistan) is not present so I am not able to use credit card to complete this transaction.  Please add my country name in billing address drop down menu or provide any other alternative."

Is there anything we can do for this guy?

**Comment by daviddurand** [comment]
I think we can enable Pakistan and a few other missing "countries" like the "US armed forces. May take a couple of days.

**Comment by orangedrink** [comment]
Thank you David. Just let me know.

**Comment by orangedrink** [comment]
Any ETA on this one?

**Comment by daviddurand** [comment]
Pakistan was added last night. On closer reading  the documentation on Paypal's site is unclear, so I don't know if they will actually accept credit cards from there, but you can pick it.

I also added two US states for certain armed forces purchases -- Military overseas can use these.

**Comment by orangedrink** [comment]
OK. Thanks!
