### ISSUE TITLE
Users reporting being charged multiple times for content

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#137]
Here is the latest email:

---

Hello Unyime-

Thank you for the information regarding the multiple payments charged to our member. Mr. Robert Delgado has explained he was charged three times ($245 each) for purchasing a Best Practices Metric. He is still requesting the material, however would to be refunded 2/3 payment he was charged. I tried to look it up on my end through PayPal  but was unable to locate his name and the amount. Can you please assist me with this process? If you need additional information, please let me know. 

10/17/2012: two payments

10/18/2012: one payment

Thank you,

---

And here is another that sounds like a similar problem:

---

Hello Cyndi, 

It has come to our attention that some how during the purchasing process for online access to the 2010 HCM we were charged twice.  I received two e-mails with two different transaction ID No.s (86800215 and 86800260) for the same user name "chowing@rkagroup.com".  We do not want two access names to the site and would like the second charge to be reversed.  

Thanks, 

On Tue, Sep 18, 2012 at 12:25 PM, TRBSales TRBSales@nas.edu wrote:

Cody:

Register Your HCM Today

Using your web browser, go to www.HCM2010.org; enter your unique HCM 2010 serial number (see below); create a user login and password using your e-mail address.  This registers you for an account to access volume 4.  The serial number below is case sensitive and can only be used to create one account – therefore, do not share it with others.  

HCM 2010 Serial Number:  RHDN9xY

If you need anything further, please let us know. 

Best regards,

Cydni Johnson

Transportation Research Board

---

Thank you David. Let me know if there is any other information that you need.

**Comment by daviddurand** [comment]
We've added a javascript that disables the button after form submission and changes the button to a "wait" message. This should do a lot to reduce multiple presses. According to PayPal, clearing a credit card can take up to a minute, though usually much less, so they advise an explicit note to that effect. You may want to consider including that in your site copy.
