### ISSUE TITLE
Get Tizra Error when Trying to open a page layout

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#139]
I'm working on updating TRBs site with a new template and content. http://amonline.trb.org/

I just saved the updated information from staging, and then applied the live site to staging so I could see how a couple things in the sidebar was setup. 

After doing that I went into "Home > Presentation > Layouts" and got an error when I clicked any of the Page Types.

I tried to copy the text out of the pop error that I got, but I am not able to. Here is a screen shot: http://screencast.com/t/eBw00XlRx

**Comment by daviddurand** [comment]
It looks like you cleaned up all the old designs, and the workbench contained some blocks (probably master blocks, or contents of master blocks) that were part of the old designs -- it's now triggering a database error that a block in the workbench doesn't exist. This is a stale cache problem and should resolve itself.

In fact it's OK now.

**Comment by ghost** [comment]
got it, thanks.

**Comment by ghost** [comment]
This is happening again. I have not deleted anything, only updated a static page and added some css.

**Comment by ghost** [comment]
Closed all tabs with the site on it, waited and then logged in after 5 minutes or so. Everything seems to be working again, but if you know what may have caused this I would like to know.

**Comment by daviddurand** [comment]
From the logs is looks like you may have run into some trouble with a master block sitting in the workbench that was defined in a layout that was subsequently deleted. Dragging the master block into a new layout may have then caused the problem.

I've tried to moderate the system behavior in more of these cases, but there are longstanding issues with moving master blocks between designs on a permanent basis. In this case, caching may not have been involved, but I can't tell for sure with the information I have.

One thing to watch for is the "Foreign block" notation that may appear on a master block in red. If you see that, it means that there's a mix. You can either replace such blocks with ones that are defined in that design, or disaggregate the block and redefine it in that design.

Another approach would be to empty the workbench before (or after) deleting a lot of designs.
