### ISSUE TITLE
Error when doing a list publish of collections

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#145]
When publishing collections on AI I get this error.

http://screencast.com/t/fFSjrMHu4

**Comment by daviddurand** [comment]
I found an error message in the logs, and it looks like it may be a problem in the list selection code -- not the publication _per se_. I'm going to investigate now, but if you don't filter the list, the publish should work properly. Once I can replicate it, a fix should follow shortly.

**Comment by daviddurand** [comment]
Fix is going in place now.
