### ISSUE TITLE
Author Index letter links bringing me to Title Index

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#150]
When I click on the Author Index link in the menu bar of my site, I correctly go to the list of ALL authors page: 

http://cbw.tizrapublisher.com/~bookindex?indexLetter=ALL&indexField=Authors

BUT, when I click on a letter to go to a specific list of author last names ending in that letter, I'm brought to the TITLE INDEX page. Here is the letter P: 

http://cbw.tizrapublisher.com/~bookindex?indexLetter=P&amp;indexField=Title

**Comment by daviddurand** [comment]
Fixed, thanks.
