### ISSUE TITLE
Having trouble deleting documents

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#152]
I'm trying to remove all of the documents from the BS site. I'm using the list view and clicking on "view all xxx documents" and then deleting them. I get this error.

http://screencast.com/t/ypp3PUdz

**Comment by orangedrink** [comment]
I need to move forward with this job so I'll delete them a few at a time as I'm able. Sorry if that makes this hard for you to reproduce.

**Comment by daviddurand** [comment]
This is must be due to a search index updating problem in the past (perhaps a failed publication), so that you are (inadvertently) trying to delete something that no longer exists. I'm making a fix to this that should be in place tomorrow.
