### ISSUE TITLE
Can't add Google analytics tracking codes

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#153]
I'm trying to add a GA tracking code to the ASPPA site. 

To reproduce go to reporting>Google analytics

Enter a tracking code and description and click save.

The tracking code is not added.

**Comment by orangedrink** [comment]
We'll be contacting you to see if we can get you to send us analytics data from your account since we aren't able to add analytics to our sites.

**Comment by daviddurand** [comment]
Sorry for the delay in this. The problem has been fixed and will be live tomorrow.
