### ISSUE TITLE
Having trouble deleting collections

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#158]
I'm removing groups of documents and their collections from handouts.sde.com. I'm able to remove the documents without issue but then when I try to remove the empty collection I get this error:
http://screencast.com/t/bDlpLPxWLvm8

If I retry a few times I'm eventually able to delete the collection but this makes the process a little more difficult.

Thank you!

**Comment by daviddurand** [comment]
I couldn't track this down, but the error reporting should be improved if it happens again. Reopen the issue if it recurs and there's a way to investigate it.
