### ISSUE TITLE
Unable to update loading image on amonline.trb.org

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#159]
I'm trying to update the image named 'loading' on amonline.trb.org

This is not a site property but an image at "Home > Presentation > Images > loading"

I click Choose File, browse to the new file, click open and have tried then clicking save and publishing to live and staging with no luck.

Thanks.

**Comment by orangedrink** [comment]
This did update eventually. It just took a few minutes.

**Comment by daviddurand** [comment]
probably browser cache.
