### ISSUE TITLE
Unable to publish to live

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#163]
To reproduce go to the static page named "2013 Subject Index" on amonline.trb.org and try to publish it to live.

I've been seeing this with collections as well.

Let me know if you have any questions.

**Comment by orangedrink** [comment]
Any progress here? We need to be able to publish to live.

**Comment by orangedrink** [comment]
It sounds like Paul is having a problem with publishing things on http://lars53669.tizrapublisher.com as well.

Not sure if this is related.

**Comment by orangedrink** [comment]
Paul's site was supposed to go live today. 

TRB will need to be fixed by tomorrow in order for us to stay on schedule.

Could you at least confirm that you know about the problem?

**Comment by daviddurand** [comment]
I found a problem in error reporting, which was causing the message on a publication problem to be suppressed, and that is why you were not getting the silent publication failure.

I'll follow up here once I've got the fix in place.

**Comment by daviddurand** [comment]
It's a maximum number of pages problem. I'll bump up the plan, and you guys and Abe can work out the financial details later.

**Comment by daviddurand** [comment]
I published the static page once I pushed the page count up. I don't have any details to test Paul's problems, so I can't do more on that. Open a fresh ticket with a  detailed bug report if there's something I need to do there. Now that the messages are showing up again, you may be all set.

Sorry about slow response, but it's Christmas. In an emergency, you should definitely call.
