### ISSUE TITLE
Unable to update Practice ready property on papers on amonline.trb.org

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#164]
After you had mistakenly changed the Practice Ready Property to a boolean type I tried to set this back to a string and use the list tagger to set all of the documents with a value of true to yes and a value of false to blank. I'm able to see these changes reflected on the back end but the front end is still returning a true/false value

To reproduce see the first paper retuned in these search results: http://s34541459-preview.tizrapublisher.com/~searchResults?searchMode=advanced&searchText=&searchParam-Subject=&searchParam-SessionNo=&searchParam-Title=&searchParam-PaperNo=&searchParam-AuthorListSortable=&searchParam-Organization=&searchParam-committee=&searchParam-year=2013&searchParam-Practice=true&searchParam-type=+

Then check the practice-ready property of this document on the back end (making sure not to confuse it with the "bool practice" property which is and should remain a boolean)

Thanks.

**Comment by orangedrink** [comment]
Here's a screen grab: http://screencast.com/t/XBuePDIqec

**Comment by daviddurand** [comment]
Sorry I changed the type; I thought it was a new property, but I may just have been completely mistaken.

If you change a type, any documents that were published with the old type will need to be republished once you have changed the type. If you've been making changes in content management, running the supertagger over the new documents first will ensure that the content management index is up to date as well. You can even run it without changing any properties, and it will re-index each document.

The content-management index will affect property filters only, not what gets published.

Looks like you are republishing now, so my guess is you figured this out...

**Comment by orangedrink** [comment]
I think it just took a long time for the changes to come through on the front end. They look right this morning.

Thanks David.
