### ISSUE TITLE
Can't edit collection on amonline.trb.org

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#166]
When I click on the collection named "Past Documents (2011 - 2012)" I get the following error

http://screencast.com/t/QUhhewXj

**Comment by daviddurand** [comment]
Can you tell me what you were doing on the site just before you noticed the problem? it seems like it may have been a stale database cache issue, as I can't see the problem any more.

**Comment by orangedrink** [comment]
I was using the list tagger to tag a bunch of documents.

**Comment by orangedrink** [comment]
I was able to edit the collection a minute ago but now I'm getting an error again.

**Comment by orangedrink** [comment]
I'm intermittently able to open the collection but when I can I see this

http://screencast.com/t/YFngJyGM4uG

And then I get sporadic error messages when trying to work with the tag picker. Sometimes they look like:

http://screencast.com/t/d1r733I3

But most of the time I'm seeing:

http://screencast.com/t/mxKLiYlPXOd
