### ISSUE TITLE
Document filtering

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#170]
The filter for documents use to stay filtered after finding, editing and publishing a file so that you could return to your filtered list and find another document that fit the same filtering criteria. Now the filter resets any time you go back to the document list. 

I only post this because I wasn't sure if this change was on purpose or if it was something that happened with another update.

Thanks,
Ryan

**Comment by daviddurand** [comment]
Can you give an exact sequence and site, as I tested on one of mine, and was able to set a filter, click on a document in the colum browser, save changes, publish, and then click on documents in the content browser, and I still saw the filtered list.  clicking on the "Books" link in the breadcrumbs also preserved the filter.

Clicking on "Home" does not, but it also takes you back to the main admin page, and to my knowledge, it has never preserved the filter properties -- that's one of ways to reset them...

are you getting back to the list in some other way?

**Comment by ghost** [comment]
Yesterday I tried multiple ways to return and no matter what I did the filtering was removed... but with that said, it worked fine this morning.
