### ISSUE TITLE
JSON problems on NFXF Site

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#171]
To reproduce visit this URL

http://nfxf.conferencespot.org/api/query?tizra-id=2bi0b4

**Comment by daviddurand** [comment]
I had just noticed this. It was a deployment problem. I will restart with a fix shortly.

**Comment by daviddurand** [comment]
working again.

**Comment by orangedrink** [comment]
It's just throwing a different error..

**Comment by daviddurand** [comment]
Found the problem. This recurrence of #171 may have happened in the SDE
recovery. It's working now, and should not recur.

**Comment by orangedrink** [comment]
OK thank you.
