### ISSUE TITLE
can't open https://secure.agilepdf.com/site/welcome

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#172]
when i try to open https://secure.agilepdf.com/site/welcome

i get this error page:

Error: Unknown Tizra Error

If this looks like a bug, please send us a note describing what happened, and we'll try to get things fixed as soon as we can. providing us details on the steps leading to this error. We'll get back to you as soon as possible.

**Comment by daviddurand** [comment]
this was fixed.
