### ISSUE TITLE
SDE Login Issues

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#173]
SDE has 5 events starting today and people trying to setup their accounts can not. When trying to login for the first time the user enters their username and then clicks login to create the password. When they click login, the site doesn't go to the claim account page as it should, but just refreshes the home page and clears any entered information.

Site: http://handouts.sde.com/
After login attempt it goes to: https://secure.agilepdf.com/registeruser/1ehsl7?registrationStep=claimAccount&emailAddress=hoodr479@gmail.com

Video to demonstrate the problem: http://screencast.com/t/GIoRXGetgGVE

**Comment by daviddurand** [comment]
We just tested two other sites and found out that it seems to be happening to more sites then just sde.
Not sure if this helps you, but I thought I would let you know.

Thanks,
Ryan

**Comment by daviddurand** [comment]
Found the problem. Fix will be live shortly.
