### ISSUE TITLE
Uploader not working 

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#181]
http://screencast.com/t/IGmd46QZFD

I took this video of what is happening when I try to upload a file to ASPPA. I'm trying to update the staging site with new files so they can proof the new content without disturbing the live content. No file appears after I remove the old file and upload the new file and then upload to staging.

I really need to get these files online this morning for them to proof while I build another section of the site that needs to be on staging today as well.

Thanks,
Ryan

**Comment by daviddurand** [comment]
Thanks for the movie. You'll have to send me the PDF file, as it's not file upload that is broken in general. I uploaded a random PDF and published it to staging without trouble -- It's still sitting there, but will need to be removed.

I've been trying to make the error alerts less painless in the admin generally, and perhaps some upload message is being eaten.

It would be good to have the URL of the site and at least the name or URL of document in text forn as well -- I had to watch the movie a couple of times to get all the details.

**Comment by daviddurand** [comment]
Previous post seemed not to have gone through, but it put it in the log anyway.

From Ryan in emai:

> I don't know what has changed, but I just tried two of the files again and now it is processing correctly and showing up on the staging site.
> If it happens again I'll let you know. I don't want to keep trying to upload the same file and cause publishing problems.

I'd still like to see the file in case there is something to learn there.

**Comment by ghost** [comment]
I'll send you a file or two so you can investigate.
