### ISSUE TITLE
Publishing Collection to Staging impacts Live

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#188]
I'm trying to publish the title of a collection to staging but continue to get a title change on the live site as well.

Site: http://elibrary.asppa.org/erisa-outline-book/
Collection Name: 2012 ERISA Outline Book
Collection ID: 1v8i8n (66341143)

**Comment by daviddurand** [comment]
You are correct.

I'm sorry to say that is the way that it's supposed to work. I agree that it would be nice if the Collection name were metadata like the the title of a document is, but like the name of an offer and custom URLs for everything, it's something that changes immediately. If a note to this effect is not in the manual, let me know and we'll get one in place.

If I could make the change in an easy, backward-compatible way, I would, but the rare inconvenience has not justified the relatively substantial amount of work to the correct this.
