### ISSUE TITLE
Unable to change email address on amonline.trb.org

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#189]
When trying to change my email address on the page:

https://secure.agilepdf.com/edituserdata/23efev/~editUserInfo

After clicking submit changes it reverts back to the original.

Thanks!

**Comment by daviddurand** [comment]
I think this may have to do with the SSO setup. I'm going to investigate.

**Comment by daviddurand** [comment]
This is fixed, change will be live tomorrow.
