### ISSUE TITLE
Tagged static pages not appearing on AMIA 

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#190]
Some of the 2012 conferences have layout overrides with list blocks that are set up to list frontal materials which are stored as static pages. As far as I can tell the list blocks are set up correctly and the pages are tagged with the correct tag but these frontal list block don't show any content.

See here for an example.
http://proceedings.amia.org/CN2012-nav/

the collection in this example is called "2012 11th International Congress on Nursing Informatics"

**Comment by daviddurand** [comment]
It's a problem in the admin tag filtering. Tag filtering for tags that contain a hyphen `-` are being escaped to prevent potential parsing errors (this is a change that was related to removing ways that end-users could create search errors by searching for strings that are significant to Lucene).

If you need a short-term workaround, you can create collections for the lists and use those. A fix will be in place before tomorrow.

**Comment by orangedrink** [comment]
OK thank you

**Comment by daviddurand** [comment]
I gave  a stupid workaround. If you use tags without hyphens, it will work just as you had the setup, with filtering and all.

That is probably your best bet.

**Comment by orangedrink** [comment]
As long as it's working now. Thank you.

**Comment by daviddurand** [comment]
Yes, we are good now. Thanks for the report.
