### ISSUE TITLE
Having trouble with referrer authentication

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#192]
I'm using a firefox referrer addon to test this. It's possible that the problem is with my testing. Is there a way to make sure this works before sending to the customer?

See the linked video for a demonstration http://screencast.com/t/mwmGL4pyBXr

Thank you

**Comment by orangedrink** [comment]
I think it's probably worth pointing out that I don't have a field for SSO token on my advanced site properties page as outlined in the documentation I'm using.

**Comment by adane** [comment]
My fault.  I just hadn't set it up properly.  You should be all set now.

**Comment by orangedrink** [comment]
Ok thanks
