### ISSUE TITLE
Truncated Bookmarks

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#193]
Long bookmarks in PDFs are being truncated.

**Comment by ghost** [comment]
I tried to add the missing text into the table of contents for the file. 
When trying to save the changes, the system freezes for a couple minutes.
After the freezing has completed, I try to publish the changes, but nothing changes.

I need the full bookmark text in all of the bookmarks but the system is not allowing me to do it.

**Comment by daviddurand** [comment]
The database schema has a limit of 25 (normal database limits). I have changed this to an unlimited length, reopen if this does not solve your problem.
