### ISSUE TITLE
Transaction failed error message when trying to purchase offer

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#194]
I get this error message when trying to make a purchase on aga53756.tizrapublisher.com. We're not sure what it means. We know the card is working and the information was entered correctly.

Transaction Failed
Your purchase was not successful. Your card may have been declined, or you may have entered the information incorrectly. The error message is:

Security header is not valid

**Comment by daviddurand** [comment]
This means that the API credentials for paypal are not correct.

This can happen if you are try to use the paypal fulfiller on the testing site against paypal on the staging site, or if you are configuring a customer paypal account and the credential is not correct.
