### ISSUE TITLE
Error when replacing paper

### ISSUE THREAD

**Issue by PStokesOmni** [Tizra/Tizra-Customer-Tracker#195]
I am trying to replace an existing paper on http://sar53627.tizrapublisher.com

When publishing to staging and live I get this error.

> Error
> com.cubchicken.common.control.TizraException: I/O error in PDF parsing
> on operation editObject

When publishing the same PDF to staging I get this error.

> Error
> com.cubchicken.common.control.TizraException: could not set MetaFile contents
> on operation editObject

**Comment by PStokesOmni** [comment]
I redistilled the PDF and now get a new error:

> Error
> com.cubchicken.common.control.TizraException: Could not allocate destination files
> on operation editObject

**Comment by adane** [comment]
Thanks for the report, Paul.  We're looking into this now.

**Comment by daviddurand** [comment]
It turned out that there were intermittent, but escalating problems on the temporary files disk drive. This was leading a variety of issues in various areas of the system. We've now got a replacement online and operations are back to normal.
