### ISSUE TITLE
Any Changes made to attachments recently?

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#198]
We have some links to attachments (on documents) on the AI site that have stopped working today. Have you made any changes that would explain that?

Here's an example of a link that was working until recently

http://knowledgecenter.appraisalinstitute.org/content/stream/822-spreadsheets/cms?sourceFileOrder=0&sourceId=Attachments

**Comment by daviddurand** [comment]
I'm sorry about this, but those are not links that should have been used. Links of that form were used internally to the admin interface to download the content management version of an attachment….

If you want to let a user access an attachment use the standard form of link. The standard links are shown in the Admin interface right under the attachment:

![admin interface snap](https://f.cloud.github.com/assets/1316941/287969/a1f338ce-9265-11e2-8648-27c1d09d2fa6.png)

there is an alternate if you really want to use index numbers:
`~~Attachments/0` (first attachment, if you are using the index of the attachment, but much better is to use the filename of the attachment)

You have traditionally used ~~PdfSource/0 to access the original source of a paper, and that is the delivery method that the new watermarking targets.

The absolute links are `http://site/object_URL/~~Attachments/whatever`, but as always it is best to use the relative link, as that will work correctly on live, staging, etc....

If you have hundreds of such links to adjust, I could restore them temporarily, but it would be better just to change them now.

**Comment by orangedrink** [comment]
Neve rmind that last comment. this was something we has set up after all.
