### ISSUE TITLE
Copyright Line generated by New Reader Print Page Option may not be appropriate

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#199]
Printable pages generated via the single page printing feature accessible via the sidebar button on the new reader include a copyright footer indicating that the site owner is the copyright holder, which is sometimes not correct.  

There should probably be an option to turn off the watermark or customize it.

![2013-03-25 02 52 36 pm-3](https://f.cloud.github.com/assets/1355614/299529/51fe7c46-957d-11e2-97a7-9e3df4eb5e83.png)

**Comment by daviddurand** [comment]
This message can be turned off if a site disables watermarking, using the new feature implemented as a result of #215. Will go live this weekend.
