### ISSUE TITLE
Page counts not being reported for AI

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#200]
In the admin panel on the site http://ai.tizrapublisher.com/ I click on my account and see 

http://screencast.com/t/iI6IxezXY

With 0 pages being reported. Let me know if you have any questions.

**Comment by daviddurand** [comment]
Thanks... The bad news is this won't be fixed before tomorrow. The good news is that you won't run into any page limits as a consequence, and that we already have a fix for the problem.

**Comment by daviddurand** [comment]
This is fixed. I notice, however that the DNS mapping for `http://knowledgecenter.appraisalinstitute.org/` does not appear to be working....

**Comment by orangedrink** [comment]
Thanks David. That url is working for me now.
