### ISSUE TITLE
Error when unpublishing

### ISSUE THREAD

**Issue by PStokesOmni** [Tizra/Tizra-Customer-Tracker#204]
on the site s92834083.tizrapublisher.com I get the error below when trying to unpublish papers

Request failed. Error sent back: >>

<msg>

```
        <status>error</status>
            <text><![CDATA[
<p class="t-error">

</p>
        <p class="t-error">Hibernate error:
```

org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [com.cubchicken.cms.model.MetaSource#114947394]            </p>
            <p class="t-error">operationErrorMessage:
Rolled back database transaction            </p>
    <p>on operation unpublishList</p>
        ]]></text>
</msg>
<<

**Comment by daviddurand** [comment]
There was an issue that should be resolved now.
