### ISSUE TITLE
Index missing metadata on static export

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#206]
We're trying to do a static export of http://knowledgecenter.siam.org/

On the site our index looks like this:
http://screencast.com/t/DjxD0XYalW

But when we do a static export we get:
http://screencast.com/t/1OmBUTH3W

We're having the same problem with the author index.

**Comment by orangedrink** [comment]
This was supposed to proof today so anything you can do to get to it ASAP is appreciated.

Thanks!

**Comment by daviddurand** [comment]
have been working this all morning. hope to have a fix soon.

**Comment by daviddurand** [comment]
This is live, and seems to be exporting the SIAM site correctly, so you should be good to go.

**Comment by orangedrink** [comment]
Thank you
