### ISSUE TITLE
Static Export

### ISSUE THREAD

**Issue by PStokesOmni** [Tizra/Tizra-Customer-Tracker#209]
I am doing a static export on site s117340545.tizrapublisher.com
I am finding that the ePosters index in the export is not in the same order as the site, everything needs to be in the same order.
Please advise.
-Paul

**Comment by daviddurand** [comment]
This is a duplicate of #177, which somehow got away from us. We'll start on fixing this. I'm closing this issue, and will follow up on the old issue -- which keep the history clear from first report to final fix.
