### ISSUE TITLE
Error when saving layout

### ISSUE THREAD

**Issue by PStokesOmni** [Tizra/Tizra-Customer-Tracker#21]
I get the following error in a pop up window, when saving a layout design

"on operation updateOneDesign"

I cannot proceed.

**Comment by daviddurand** [comment]
What site is this happening on?

Are you doing save, or save as...

**Comment by daviddurand** [comment]
Thanks for the site details update.

I've found the source of this, and it is affecting multiple sites. We are hoping to do a patch restart later today (for issue #20), and the fix for this issue will be in there as well.

We are very sorry for the disruption in the meantime.

**Comment by orangedrink** [comment]
I have some changes to make to TRB. Any idea what time the fix will be in place?

**Comment by PStokesOmni** [comment]
sorry, aaoscoursematerials.com
1. click presentaion
2. click library
3. Current design, click save
4. click save on popup
5. get error message

**Comment by orangedrink** [comment]
Any ETA on a fix for this?

**Comment by daviddurand** [comment]
It's now in place. Sorry for the delay, it was a busy day, and hard to find a good time to put the patch in.
