### ISSUE TITLE
Staging Cart Switches to Live when Buy Now is clicked

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#212]
When testing checkout flows in the staging site, the user is switched to the live site and design when the "buy now" button is clicked in the cart.

To reproduce...

1) While logged into staging as an Admin user, add an offer to the shopping cart.

2) Click the Buy Now button in the cart.

3) You'll arrive at the first checkout page, but will be in the live site with the live design.

The problem this causes at the moment is it makes it hard to do design on the checkout pages.

**Comment by daviddurand** [comment]
The testing area works properly, and is where e-commerce testing should take place.

I'll look into the staging area, just because it could be confusing.
