### ISSUE TITLE
New reader page count

### ISSUE THREAD

**Issue by GWPublisher** [Tizra/Tizra-Customer-Tracker#214]
Can you add a css class for the “(of XXX)” part in the new reader's title?  We would like to hide it due to the logical page numbers.  Thanks.

**Comment by daviddurand** [comment]
The classes and markup  that were in the old reader are now in place in the new reader, so you should be able to use the same CSS.

**Comment by GWPublisher** [comment]
Can we add the word page before the number?  I thought that was already there.
