### ISSUE TITLE
Sort Value on Document source files not working

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#223]
Load multiple PDFs into a single document (either from cog icon > create new > document OR right from the Document Properties screen).
Add Sort Values.
Click Save or Publish.
Sort Values disappear from field and no change is made to how the PDFs sort.
Go into the TOC, rearrange the entries (up/down) to create correct order.
Click Save.
Entries revert back to original order.
NOTE: PDFs being loaded in this test were ones in which the file name was also the name of the bookmark in the TOC (i.e. There were no other bookmarks imported as part of these PDFs BUT the PDF file name). 

TESTING USING PDFs that contained multiple bookmarks within them:
When I rearrranged the TOC using PDFs that contained multiple bookmarks/TOC headings, those moves up/down DID work. (although Sort Values still did not work on these PDFs).

**Comment by daviddurand** [comment]
This is working now. There's a bit of conflict between the outline editor (which lets you move files around), and the sort fields. The bookmark editor shows things in order (even if there were sort values), but after you save from the bookmark editor the sort values vanish, and the order is as selected in bookmark editing. This seems like a sensible compromise.
