### ISSUE TITLE
User Account Tag Picker Doesn't List Available Tags

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#226]
After new tags are created and saved in one user account, those tags do not appear in the tag picker screen for other accounts within the same site.  See attached.

![Screenshot 4:29:13 10:44 AM](https://f.cloud.github.com/assets/1355614/439065/977b48ca-b0db-11e2-8372-27f188e973c0.png)

**Comment by daviddurand** [comment]
This was a problem with the indexing of user tags. If the tags are way out of sync for a site, we can re-index, though there is no significant effect except on the prompting.
