### ISSUE TITLE
Problems editing an account in SDE

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#230]
When I try to bring up this account in the back end

wildwildes@yahoo.com

The page never loads (I do see the loading graphic but it never goes away)

Let me know if you have any questions.

**Comment by daviddurand** [comment]
Thanks for letting us know about this. The account had logged in today at some point, but there had been a database deadlock. This has never happened to us before, but it's a known Postgres behavior, and once I cleared the stuck transaction, everything was good.

Thanks for the report.
