### ISSUE TITLE
t-old is appearing on new and old sites

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#233]
I was under the impression that we had removed t-old from our sites, but our new sites no longer have the option to remove it, and it seems to have appear again on some of our older sites.
Because of t-old showing up, we are having some site links break. 

Is there a reason that t-old is back, or is this just a bug that slipped through?

Thanks.

**Comment by daviddurand** [comment]
You have to have the supportOldMarkup advanced property available, and then turn it off...

It's probably not there for all your sites (or it's not set properly, if it is there). We can enable this for any site if you request it through the normal channels.

**Comment by ghost** [comment]
Every one of our emails for site setup includes the following, so I thought you had changed something since the old markup is showing up... 

Please include the following settings as part of the site setup:

1) EnableIE7Compatibility = No
2) supportOldMarkup = No
3) allowSiteExport = **\* No ***

**Comment by ghost** [comment]
To be more specific, on May 1 we requisitioned 52712/FLASHA. The email that was sent looked like this:

Hello publisher-support@tizra.com.

Please create a Tizra site for **\* 52712/FLASHA **\* as follows:

1) Provision the site with **\* 500 **\* Pages
2) Create a subdomain for the site of **_flasha52712**_
3) Set up the initial admin user account for **\* ---@omnipress.com **\* 
4) Copy design **\* Design Template 1 - Left sidebar **\* From templates.tizrapublisher.com to this site. 

Please include the following settings as part of the site setup:

1) EnableIE7Compatibility = No
2) supportOldMarkup = No
3) allowSiteExport = **\* No ***

Thanks!

But, the site settings do not include "supportOldMarkup" as an editable item for our technicians, and isn't being setup by Tizra at site setup.

**Comment by ghost** [comment]
I was just finishing up a list of sites that still had t-old and it looks like you must have been going through and correcting this. Thank you.

**Comment by cbwinchild** [comment]
Hey Ryan,

I fixed the sites that were improperly set up. If you notice one still
missing the SupportOldMarkup field, please just let me know.My apologies
for any inconvenience.

Thanks and have a great weekend.

Catherine

On Fri, May 10, 2013 at 2:21 PM, Ryan Hood notifications@github.com wrote:

> I was just finishing up a list of sites that still had t-old and it looks
> like you must have been going through and correcting this. Thank you.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Tizra/Tizra-Customer-Tracker/issues/233#issuecomment-17736263
> .

## 

Catherine B. Winchild
Technical Writer
Tizra, Inc.
9 Catalpa Rd.
Providence, RI 02906
_Phone:_ +1 (855) 220-1235
_Fax:_+1 (401) 273-5171
