### ISSUE TITLE
Staging and Live both aren't showing changes

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#235]
Working on aarp54390. Applying changes to a static page (Feedback). After making changes and then saving and applying to staging and live, nothing is happening on staging or live after refresh. EX: Changed h2 tag to h1 tag and added span tags to header text. Added class to p tags. Saved and applied to staging and live. Shows correctly when looking at the code on the page. When looking at staging and live, still shows h2 tags and p tags have no class. Tried this in both Chrome and Firefox.

**Comment by aabercrombie** [comment]
Just noticed that my Wufoo form, which should be pulling through from Javascript in a free HTML block, is also no longer coming up on the same static page.

**Comment by adane** [comment]
We're working on it.  The quick workaround for the moment would be just to create a new static page and paste the updated HTML into it.  If you need for it to be at the same URL as the one you're having problems with, you can cut the contents of the Custom URL field out of the problem one and paste it into the new one.

**Comment by aabercrombie** [comment]
The HTML tags showed up fine on a new page, but the Wufoo form still isn't showing up. Just thought you guys should know.

**Comment by aabercrombie** [comment]
Publishing is working fine, but the HTML block with my Wufoo form still isn't showing up.

**Comment by daviddurand** [comment]
You made a custom page format override, and that template includes an HTML block with the intro text -- it does **not** include a static page content block, that would refer to the contents of the HTML editor on that page. I added the static page block back so that you can see the differences. Once you've got the the correct markup in the static page editor, just delete the old HTML block from the layout, republish, and you should be good.

**Comment by aabercrombie** [comment]
The text is showing up, but the wufoo form is not. I did originally try to put the Javascript into the HTML editor, but it won't show up. So I added a free HTML block below it to paste the Javascript embed code into. This worked just fine until the site started messing up yesterday. This morning, after reading your message, I created a whole new page (called Feedback), put the HTML intro code into the text editor, and tried to add the Javascript to it as well. No go. So I went and added a free HTML block below the static page content block to put the code into, since I don't know a better way to do that and it worked yesterday. Still no go. 
Since I'm obviously still doing something wrong here, can you please fix it for me? Use the Feedback page http://aarp54390.tizrapublisher.com/feedback/. The code for the form is in the free HTML block.

**Comment by adane** [comment]
Hi Alicia--

Unless Tizra is somehow not functioning as it should, this sounds like something one of your in-house web developers should handle.  

Let me know if I'm missing something.

Abe

**Comment by daviddurand** [comment]
One thing to bear in mind is that you can use the view source option of the HTML editor to make sure that it has not messed up your javascripts. Most people put scripts into an HTML block to avoid potential problems, and leave the normal text in the HTML editor. We can't debug scripting problems, only cases where the scripts are somehow not being delivered properly.

**Comment by aabercrombie** [comment]
The text is in the static page block and the scripting is in the free HTML block just like you said, so I'm not sure what the problem is. I always view the source when editing HTML on Tizra instead of using the rich text editor, esp on a site this large with so much CSS.  It worked yesterday morning before the site went wonky for a bit, so I thought you guys might have missed something. Either way, I have Dave Franks looking into it, so we'll figure it out.
