### ISSUE TITLE
Can't upload files to site that still has pages

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#249]
Trying to add file to CMBA Gold 1 site. They still have several thousand pages available. Can't publish any more files to either staging or live. I get this error message repeatedly. They're at a conference now so this needs to be done ASAP!
![2013-06-07_1030](https://f.cloud.github.com/assets/3876308/624531/a97598f8-cf87-11e2-9775-5fe5e189e9e6.png)

**Comment by ghost** [comment]
Site with issue is: http://knowledgecenter.clemetrobar.org/

**Comment by daviddurand** [comment]
Thanks for this. fixed. I tested an upload and published "leboef"  to staging, just to make sure.

**Comment by ghost** [comment]
Ali is testing it out and will reach out to our customer. Thank you for getting this fixed quickly.
