### ISSUE TITLE
Calendar position on New License Creation goes off the page

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#25]
http://screencast.com/t/9GUUFqqZg

I only bring this up because I know that I ASPPA will ask why the calendar goes off the page.
Is there any way that you can fix the positioning so that it stays all the way on the page?

**Comment by daviddurand** [comment]
This has been fixed, but you will have to empty browser cache and/or do a force reload to get the new version of the javascript in place.
