### ISSUE TITLE
User Info page when not logged in

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#252]
Is there any way to change what the ~UserInfo page says when a user isn't logged in? Right now it just has "Don't have any account? You can register for one now.", I couldn't seem to find anywhere to actually change what that says. Thanks!

**Comment by adane** [comment]
Hi Kuhrt--

You can change the contents of that page in PRESENTATION > Layouts.  The relevant layout is called...

All Users Info

The main content of the page is generated by a block called...

User Account Information

If you don't like the text that block generates for unauthenticated users, you can hide it with CSS, then use a Free HTML block to present different text.

If you want that text to be visible ONLY to users who are not logged in, use a macro like this...

```
%IF_CONTEXT_VALUE_BEGIN(LOGGED_IN,FALSE)%
your text here
%IF_CONTEXT_VALUE_END%
```

Further information on using the design tools is located at...

http://support.tizra.com/Tizra_Help_Manual_v1-3/244

Please let us know if we can be of further help.

Abe
