### ISSUE TITLE
Attachment links in PDF go to a page that says "undefined"

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#254]
All of our attachments in our pdfs are just linking to a page that says undefined now. You can download them fine if you click the downloads button on the left, but from the pdf they just take you to that page.

**Comment by adane** [comment]
Thanks for the report, Kurht.  Apologies for the problem, and please let us know if you see further issues.

**Comment by Kuhrt** [comment]
Thank you guys so much. Y'all are awesome!
