### ISSUE TITLE
AddThis Widget Issues

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#259]
From Henry...

In the Share smartblock, the AddThis widget icons have three problems.

1) They don't show focus. This is something I will fix.
2) The + menu doesn't respond to keyboard navigation.
3) The + menu stays open even when the + icon loses focus.

The latter two problems are javascript related. Do you have any thoughts about how to adjust the third party javascript for accessibility?

One easy solution: Get rid of the + icon.

**Comment by adane** [comment]
I'd kind of be surprised if accessibility for the AddThis stuff is important for ARL.  Am I wrong?

I have a feeling that the AddThis code in the Master Block may be a very old version.  Maybe just pulling in the current version would help?

**Comment by daviddurand** [comment]
Addthis markup is really not under the control of Tizra, except for where it is encapsulated. I'm closing this.
