### ISSUE TITLE
Beta Reader: Home Icon Doesn't LInk to Home

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#267]
When beta reader is switched on, the Home icon in the header doesn't seem to be linked anymore.  Same readerMarkup works fine when you switch back to current production reader.  Following is readerMarkup in the example I used...

```
<div style="margin-left:100px;"><a href="." rel="external" data-role="button" >Document Details</a> <a href="/~bookindex?indexLetter=ALL" rel="external" data-role="button" >Browse Titles</a> <a href="/~bookindex?indexField=Authors&indexLetter=ALL" rel="external" data-role="button">Browse Authors</a></div>
```

**Comment by daviddurand** [comment]
closed by a545851726217c1203b6e1b888e0cc1721c2d74a
