### ISSUE TITLE
Mobile Viewer doesn't show images on kindle fire

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#269]
The mobile viewer on library.asppa.org does not work on kindle fire. The images show up as a question mark.

Viewer works fine on iPad.

**Comment by ghost** [comment]
Is this something that can be looked into. I feel like I should give the end user some information

**Comment by daviddurand** [comment]
Sorry, I will take a look today. We do have a fire in house.

---

David G. Durand
CEO / CTO
Tizra
9 Catalpa Road
Providence, RI 02906

Email: david.durand@tizra.com
Phone: +1 401 935-5317
FAX: +1 401 273-5171
Web: http://www.tizra.com/
Blog: http://blog.tizra.com/

Online publishing unbound.

**Comment by ghost** [comment]
OK thanks.

**Comment by daviddurand** [comment]
This is working now on my fire. We'd lost a check, so Fire was being treated like iOS and Safari, but while it matches safari, it has different image formats supported.
