### ISSUE TITLE
Filtering on Document Titles in Admin Does not Work with Apostrophes

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#273]
Titles (and possibly other fields) containing apostrophes cannot be found via the Filter feature on the main Documents list.  Clicking the "Filter" button causes the user to be returned to the Admin homepage.

See attached screenshot for an example.

![screenshot 8 19 13 2 53 pm](https://f.cloud.github.com/assets/1355614/988414/6a070054-0901-11e3-9204-d1847b3aafc7.png)

**Comment by daviddurand** [comment]
fixed
