### ISSUE TITLE
Cannot delete a document on TRB

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#274]
I'm trying to delete paper number 13-5038 but I'm getting this error:

http://screencast.com/t/MhkT2rLy9

I tried unpublishing the document, saving and a few other things but was unable to delete the document.

Thanks!

**Comment by adane** [comment]
It's possible that the problem is that there's a user with a license to the Document.  Is it OK to delete that user's license (and thereby terminate his/her access)?

**Comment by orangedrink** [comment]
Good idea.. There was a user license. I deleted it but still having the same problem.

**Comment by adane** [comment]
OK, sorry...we're looking into it.

**Comment by orangedrink** [comment]
Thank you.

**Comment by daviddurand** [comment]
These documents were still referenced by the bulk load requests that created them. I've deleted those records, so you should be good to go at this point.
