### ISSUE TITLE
Attachments and Download Headings in sidebar menu display even if attachment set to NOT "visible" or downloads don't exist

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#276]
If a document has Attachment(s) associated with it, a "Downloads" heading will display in the "Downloads" sidebar menu of the online reader, even if there are no downloadable PDFs associated with the Document.

Similarly, if a document has downloadable PDF(s) associated w/ it, but Attachment(s) are set to NOT visible, the Attachment heading will still display in the "Downloads" sidebar menu of the online reader.

**Comment by daviddurand** [comment]
Can you give a URL? This may depend on publication/visibility status of the attachments and/or downloads, so an example will make tracking it down much easier.

**Comment by cbwinchild** [comment]
sure: here's a page where there are no downloads, but the download heading
is still listed: http://cbw.tizrapublisher.com/3s8jut/1

please let me know if you need more thank this.

On Thu, Sep 5, 2013 at 2:21 PM, David G. Durand notifications@github.comwrote:

> Can you give a URL? This may depend on publication/visibility status of
> the attachments and/or downloads, so an example will make tracking it down
> much easier.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Tizra/Tizra-Customer-Tracker/issues/276#issuecomment-23890216
> .

## 

Catherine B. Winchild
Technical Writer & Trainer
Tizra, Inc.
9 Catalpa Rd.
Providence, RI 02906
_Phone:_ +1 (855) 220-1235
_Fax:_+1 (401) 273-5171

**Comment by daviddurand** [comment]
Thanks. This is not really an error, but a badly-named global header for the entire block. We recently renamed it the resources list, as it's not always downloads any more, and hopefully that makes it less confusing.
The header can be removed by redefining the text to the empty string using the reader tailoring design macros.
