### ISSUE TITLE
All sites down

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#278]
I was just told that all of our sites are down. Do you have an ETA on when those will be back?

**Comment by adane** [comment]
They should be back now.  There was an AWS problem we're still digging into.  Let us know if you're still seeing problems.

**Comment by orangedrink** [comment]
Thanks Abe.

It looks like the sites are working but are very very slow. Keep us posted on this one.

Thanks again!

**Comment by adane** [comment]
We're currently making some DNS changes that should help further.

**Comment by adane** [comment]
Performance is looking much better now.  Are you seeing the same?

**Comment by daviddurand** [comment]
The original problem was an Amazon networking problem at their east-coast datacenter, with the machines running OK, but not communicating reliably with the world at large.

As the network reliability improved we started to see elevated Domain name lookup errors. We believe that the increased traffic of people hitting refresh, or the Amazon issue itself, was also affecting one our DNS providers. While there have been few problems with the existing DNS service, we are moving the last domain from the old provider to a new one that has been more reliable.

All of the current DNS servers seem to be responding briskly again, but we are waiting for the transfer to finish.

If there are lingering DNS problems for a particular customer, refreshing the page may help (it may take several tries). Chrome keeps it's own internal DNS cache, meaning that a few quick refreshes should get access if you can't get through to the site. Firefox and IE may take longer, and restarting the browser or temporarily disconnecting the network (cable or WiFI) should clear the system DNS cache.

**Comment by orangedrink** [comment]
I only tested with ASPPA but performance looks good now. Thanks guys!
