### ISSUE TITLE
ASPPA Chapters Disappearing when publishing a new file

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#28]
http://elibrary.asppa.org/erisa-outline-book/
Chapters 3b and 6 are missing.

Just started today because I uploaded 6 new files yesterday.

I also just told my customer that they could begin proofing parts of the site yesterday.

**Comment by daviddurand** [comment]
This is the same as issue #27.
Fix is not live yet, but will be shortly.
once it's done. you will have to republish the documents afterwards.
