### ISSUE TITLE
Passwords don't save when activating new accounts

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#281]
Our secretary is having an issue that every time she creates a new user, the password doesn't save. She says she'll even do the password and save it twice and then still the teachers call saying they can't get in to their account. Usually after she resets the password again it works. Do you guys know of anything that might be causing this?

**Comment by daviddurand** [comment]
Could there be a problem with the password match on the two password boxes? They both have to be the same. I often use cut and paste to make sure that I'm not mistyping -- I seem to be able to mistype anything several times in a row -- mostly when it matters.

There's no other problem with passwords generally.

If the teachers are going to the "forgot password" page, that could create a problem, as it email their account with a new system-generated password. If their account name is not an email address, or if it's being caught by a spam filter, then they'd never get to see the new password.

I'll check the error that should be generated if the admin interface fails to update a password -- if that's not showing up, that would make it confusing.

**Comment by daviddurand** [comment]
Well, the errors on mismatched passwords on updates are working properly.
I'm seeing proper error returns on creation as well as updates. The errors are displayed by javascript. What browser is she using? Perhaps there's a problem that's masking the error from the server.

**Comment by Kuhrt** [comment]
She's using Firefox! Ok who knows, she wanted me to ask just to make sure. I'm going to watch and see what she's doing for sure! Thanks!
