### ISSUE TITLE
Can't update Main Shell

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#287]
For SMRP we are updating the design to their new redesigned look. I'm updating the main shell to reflect some of the changes they made so that updating our site is easier. When I try to update "Main Shell" with what I have so far (New Main Shell) I get the following error.

The web page you seek cannot be located, but countless more exist. Return to site home.

Also, your error dialog hijacks the whole browser so I can't click any other tabs, is HTML text, and won't let me copy the text. Not very helpful when trying to share a potential bug with you guys.

**Comment by ghost** [comment]
Now this is happening with any layout...

**Comment by daviddurand** [comment]
Sorry about the error message -- the error is a crash in an operation, not a normal error return, and the Ajax javascript is getting confused and displaying the raw response.

I think what you did was go and delete a layout, when a master block from that layout was in the workbench. That's leading to a problem when the workbench attempts to load the now nonexistent block.

That means that there should be an easy fix.

**Comment by daviddurand** [comment]
Actually it was a cache error, so I was able to flush the bad object reference. You can edit again now.

It helps to be sure that you don't have master blocks in your workbench when you delete layouts -- this is one of the master block issues that are rare, and still have to be worked around.

**Comment by ghost** [comment]
Thanks. It looks like the stuff i was working on got wiped out.

**Comment by daviddurand** [comment]
I am afraid that I probably did that while investigating the problem.
