### ISSUE TITLE
Chrome Frame

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#29]
Is there any way for us to add the ability to have Tizra sites to be displayed in chrome frame when the end user has it installed?

I tried to add it to the global header for the ASPPA site, but it doesn't seem to be working. 
I assume it isnt workgin because you have <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" /> and Chrome Frame needs <meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible"> (or a variation of it).

I would mark this as an "enhancement" if I knew how.

This isn't a high priority at all, just thought I would throw it out there.

Thanks,
Ryan

**Comment by ghost** [comment]
My meta tags that I had disappeared... 

I assume it isn't working because you have meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" and Chrome Frame needs meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" (or a variation of it).

**Comment by daviddurand** [comment]
There's a new advanced site property to allow sites to suppress the IE compatibility mode. Feel free to email us to turn it on for any site where this is a problem.

Essentially duplicated by #31
