### ISSUE TITLE
Multiple Headers Error

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#291]
We're getting the error below from a few of our attachments. We've run in to 4 or 5 this morning and didn't know if it may be something you guys could fix? We've re-uploaded and re-processed everything multiple times and still are getting this error. There's also a link to the page below. Thanks!

First attachment "Typical Energy Level" - http://ccfcs.tizrapublisher.com/managing_time_energy_culinary/4

![image](https://f.cloud.github.com/assets/4027030/1408640/fefe5a6a-3d84-11e3-8951-124b0ad14f2d.png)

**Comment by daviddurand** [comment]
Thanks. I found the problem (which only affects quite small attachments). The fix will be in place tonight.
