### ISSUE TITLE
Cannot add license for user

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#292]
Trying to add a license for collection 1 to a user on aga53756.tizrapublisher.com. Get the error below every time.

![2013-10-28_0854](https://f.cloud.github.com/assets/3876308/1420024/a0e41d2e-3fd8-11e3-81c1-b300fb3f5447.png)

**Comment by Kuhrt** [comment]
We're getting the exact same error when trying to activate a license this morning.
