### ISSUE TITLE
Course links error from 'My Account" section

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#298]
If we try to access our subscriptions from our Account section, when we click the link to the subscription and then click the actual publication link to see it in the reader, it gives us the error below. Cleared the cookies and made sure it's allowing them. Happens on all browsers. Thanks!

![image](https://f.cloud.github.com/assets/4027030/1550615/d3db0864-4e06-11e3-9a20-b7284d65ad08.png)

**Comment by adane** [comment]
Hi Kurt--

David's working on this now.  We'll let you know as soon as we have an update.

Thank you.

Abe

**Comment by daviddurand** [comment]
I've verified the bug. The links to excerpts are creating URLs with duplicate path components, and that is leading to the loop. If you delete the duplicate from the URL, you can get access, so that may help people who are panicked and urgent. We will fix ASAP.

**Comment by daviddurand** [comment]
There is a problem redirecting from excerpts to page one when tables of contents are suppressed. Fix will be in place soon.

**Comment by Kuhrt** [comment]
Good morning!

I'm not sure if this was previously fixed, I thought it was, but it's doing it again. Also, the issue we were having with html attachments is also doing the same thing it was doing. We are using the new reader now as well.

**Comment by daviddurand** [comment]
This was a classic regression, and is now fixed again. Sorry for the problem.
