### ISSUE TITLE
Users with licenses cannot access content

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#300]
Users on aga53756.tizrapublisher.com (aga.conferencespot.org) are being told they can't access content despite their licenses being correct. Have gotten emails from 5 users so far. Seems to have started yesterday, based on dates of email support requests. Specific users so far reported include: james.oglesby@verizon.net, number_cruncher77@hotmail.com, malam003@yahoo.com, meganitat@gmail.com  and tdevoll@azauditor.gov.
Some users are reviewing for exams today, so need this fixed asap.

**Comment by adane** [comment]
Sorry, Alicia.  We are working on this issue right now.

**Comment by adane** [comment]
Hi Alicia--

The issue should be addressed.  Please let us know if you see any further trouble.

Very sorry for the inconvenience to your users.

Abe

**Comment by aabercrombie** [comment]
Looks like it's all working now. Thanks!
