### ISSUE TITLE
Customers can't open their subscribed courses

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#301]
Good morning!

This morning several teachers can't log in even though their license aren't expired. We've had 20+ customers call. I can log on and get to everything fine, so I'm not sure how to recreate the issue. Thanks!

**Comment by adane** [comment]
Sorry, Kurht.  We are working on this right now.

**Comment by adane** [comment]
The issue has been addressed.  Please let us know if you see any further trouble.  Very sorry for the problems caused.

**Comment by Kuhrt** [comment]
It's working smooth as butter now. Thanks so much. You guys are so great at getting to everything and fixing it so quickly. Thank you so much for all your work!!
