### ISSUE TITLE
Two author names in the PDF do not upload into the Document Properties screen

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#304]
If I have two authors entered into the PDF's File > Properties > Description tab > Author field, and I enter the two names as such: Winchild, Catherine; Durand, David -- only the first name uploads.

Obviously, it's easily edited on the Document Properties screen, but I wasn't sure if this is a PDF limitation or an upload bug. Thx.

**Comment by daviddurand** [comment]
duplicates #299

This is the same bug.
