### ISSUE TITLE
Image not showing up for Kindle Fire HDX

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#309]
I recall this being a bug we found once before for another mobile device, but I couldn't find it and update.

We have an end user using the new Kindle Fire HDX. When you go to a paper, the image of the page doesn't load. [broken image icon appears in the middle of viewer]

**Comment by daviddurand** [comment]
Do you have the user-agent string for that device?

That's what I'll need to track down any problems (as long as the problem is not simply ability to display an image over a particular size).

**Comment by ghost** [comment]
I'm sorry, i don't know exactly what you are looking for, but I did find this for Kindle devices.
https://developer.amazon.com/public/solutions/devices/kindle-fire/specifications/04-user-agent-strings

Kindle Fire HDX 8.9" (3rd Generation)
Silk browser
See Amazon Silk User Agent in the Amazon Silk Developer Guide.

Kindle Fire HDX 7" (3rd Generation)
android.webkit.WebView
Mozilla/5.0 (Linux; U; Android 4.2.2; <locale>; <device> Build/<build>) AppleWebKit/<webkit> (KHTML, like Gecko) Version/4.0 Safari/<safari>

Kindle Fire HD 7" (3rd Generation)
Web app runtime
See Web App FAQs.

Kindle Fire HD 8.9" (2nd Generation)
Silk browser
See Amazon Silk User Agent.

Kindle Fire HD 7" (2nd Generation)
android.webkit.WebView
Mozilla/5.0 (Linux; U; Android 4.0.3; <locale>; <device> Build/<build>) AppleWebKit/<webkit> (KHTML, like Gecko) Version/4.0 Safari/<safari>

Kindle Fire (2nd Generation)
Web app runtime
See Web App FAQs.

Kindle Fire (1st Generation)
Silk browser
See Amazon Silk User Agent.

android.webkit.WebView
Mozilla/5.0 (Linux; U; Android 2.3.4; en-us; Kindle Fire Build/GINGERBREAD) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Safari/533.1

Web app runtime
See Web App FAQs.

**Comment by ghost** [comment]
David, I see that this was closed, but I don't see any change to the kindle fire hdx. The image still doesn't show up in our device.

**Comment by daviddurand** [comment]
I'll need to know which exact version is not working, and what the user-agent string is. I found a problem in detecting Android tablets, and fixed it -- it was delivering PDF instead of PNG, and that was causing problems for many android tablets. My old fire is getting proper display with an image delivered.

make sure that the caches have all been cleared in case old markup is hanging around in the browser.

If you can get any error logs from the device's browser, that would help.

**Comment by ghost** [comment]
Browser is the Silk Browser.

it appears as if the problem is when allowing the device to pick the "View option". It seems to default to "Desktop" but when it does that it doesn't load the image. When the view option is switched to mobile it loads the correct image. I don't feel like most people will know to do this on your system, so I think that the desktop option needs to be accounted for. 

I also mentioned that it was a new Kindle Fire HDX. I forgot to mention that it is the 7" version with wifi, 16GB hard drive and a 2.2GHZ Quad-Core.

I don't know what other information you are looking for, but I have found everything I possible could to share with you. If you need anything else, this site https://developer.amazon.com/public/solutions/devices/kindle-fire/specifications/04-user-agent-strings and this site http://docs.aws.amazon.com/silk/latest/developerguide/user-agent.html seem to have a lot of helpful information for developers.

here are some notes I found about this browser in the new kindle fire HDX.

Desktop
Mozilla/5.0 (Linux; U; locale; product-model Build/product-build)
    AppleWebKit/webkit-version (KHTML, like Gecko) Silk/browser-version Safari/webkit-version
    Silk-Accelerated=cloud-browsing-state

Mobile
Mozilla/5.0 (Linux; U; Android android-version; locale; product-model Build/product-build)
    AppleWebKit/webkit-version (KHTML, like Gecko) Silk/browser-version Mobile Safari/webkit-version 
    Silk-Accelerated=cloud-browsing-state

Note
Red fields are variable and are described below. [RH - not able to format the red fields they are talking about, but all this information was found on http://docs.aws.amazon.com/silk/latest/developerguide/user-agent.html]

Template fields
locale–Indicates the chosen language and country or region for the tablet. Locale is in hyphenated lowercase format, as in en-us (US English). For Kindle Fire (1st Generation), locale is always en-us.

product-model–The value of Build.MODEL (for example, KFTT).

android-version–The Android platform version (for example, 4.0.3).

product-build–The value of Build.ID (for example, IML74K).

webkit-version–Indicates the version of WebKit used (for example, 535.19). This value can change whenever the Kindle Fire receives a software update.

browser-version–Indicates the version of the Silk browser, in the format major.minor (for example, 2.1). The browser version can change whenever the Kindle Fire receives a software update.

cloud-browsing-state–This value is set to true if cloud browsing is enabled, and false if cloud browsing is not enabled. Users can change this setting on the device. When cloud browsing is not enabled, the request is sent directly to origin. When cloud browsing is enabled, the request may be sent either through the cloud or directly to origin, depending upon various factors. In other words, a value of Silk-Accelerated=true does not necessarily mean that a request was sent through the cloud.

---

Please let me know if there is anything else you need from me.

**Comment by daviddurand** [comment]
Actually that was very helpful. The "desktop" version does not set the "mobile" flag (as you would expect), but it does not admit to being android either (which I did not expect). So we were delivering PDF images as we do for all other versions of Safari.

I think I can sniff the browser properly now.

**Comment by daviddurand** [comment]
partial fix is in place. Default view selection will be fixed tomorrow after restart.

will take up to 5 minutes for cache to clear.

**Comment by aabercrombie** [comment]
Hi David,

I'm having the same issue as the Fire now, but for Android devices, both phones and tablets. This has been reported on a Galaxy S3 phone (mine and the customers) and her Acer A200 tablet and her Samsung Note 2. It looks like the default browser doesn't know to view them as images, because when I use Chrome on my phone it shows up properly as an image. 

It looks like you said above that you'd already fixed this. Can you take another look please? I've verified personally that it's an issue.
