### ISSUE TITLE
Compatibility Mode and IE9

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#31]
It seems that IE9 can't act like IE9 because we have the meta tag IE=EmulateIE7

Is there any way for us to only include the IE=EmulateIE7 with 8 and under?

**Comment by daviddurand** [comment]
I'll look into this -- We might be able to create a way to control the header content a little more precisely for cases like this. It's not going to be something that we can do right away, however, as the browser tag is there to make sure that a lot of existing sites continue to work properly -- so the enhancement will have to be a new kind of site setting, not just a quick change to the browser logic. We have conflicting development priorities for the next month or so, before anyone is likely to be able to look into that kind of approach in any detail.

One thought -- if you add your own meta-tag to the header that resets the IE behavior, perhaps it will override the setting in the header we include... also, you might be able to have an inline javascript reset the browser mode after the page loads (or at least after the header). I'd suggest investigating those to see if they might be options for an immediate way to get access to whatever markup capability it is that you need.

**Comment by ghost** [comment]
I understand and thanks for the response.

I'll try to investigate work-arounds for now.

**Comment by daviddurand** [comment]
There is a new site parameter to control this.

Also described in #29, which is essentially a duplicate, because the IE compatibility mode header is the underlying problem for both issues.
