### ISSUE TITLE
Filter Tag Picker Does Not Show Capitalization or Punctuation Correctly

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#312]
For example, in the attached screenshot, a Document titled "SAMPLE: A Natural Approach to Chemistry" shows up in the tag picker as "sample%3A a natural approach to chemistry"

![2014-01-28 02 55 06 pm](https://f.cloud.github.com/assets/1355614/2023072/4e7ba8ce-8856-11e3-8380-dfe7b9e4d8ea.png)

**Comment by daviddurand** [comment]
This is actually a feature of search engine updates. At one time these matches were case sensitive, but the field values and the index were normalized to lower case. The new system is more respectful of case, but has to present the old values until the document is republished, after which the value will look normal again.

This way of doing things looks a little weird at times, but guarantees that collections will still work, without reindexing or republishing lots of stuff, but supports the new "better" way. The indexing changes that led to this have also made tag completion much much faster...

It also supports the new author indexes based on virtual collections.
