### ISSUE TITLE
Tags aren't staying for users

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#316]
Trying to add tags to some users within the AI site (ai.tizrapublisher.com). When I add tags for a user, they stay for about 5 minutes and then disappear again. 

For example, with user cmarcordes@appraisalinstitute.org, I was trying to add the tags of aistudent and aiinstructor. When I hit save, the tags stay there for about 5 mins and then just disappear.

**Comment by daviddurand** [comment]
I believe that the this site has an SSO implementation. This means that any tags will be reset when the user logs in, as they are controlled remotely.

**Comment by aabercrombie** [comment]
Oops, yes, yes they are. Award for unnecessary ticket for the day goes to me.
