### ISSUE TITLE
Bug in Create New License Dialog

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#317]
On the user profile page, clicking the + add new license link generates the following error.  

A similar error occurs when creating licenses on Account Sets.
![2014-02-12 12 26 07 pm](https://f.cloud.github.com/assets/1355614/2151347/df341eea-940a-11e3-81cf-ba1260b21232.png)

**Comment by daviddurand** [comment]
This is caused by a bad search index entry for an offer on your site -- which will be repaired soon.

**Comment by daviddurand** [comment]
This is fixed now.
