### ISSUE TITLE
Users with licenses denied access to content

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#319]
Two users on aga53756.tizrapublisher.com have been denied access to their materials this morning despite having the proper licenses. Also had two users with the same issue on elibrary.asppa.org.

**Comment by adane** [comment]
Hi Alica--

We're working on this...please see email.

Thank you.

Abe

**Comment by adane** [comment]
We just put in a fix.  Can you let us know if you're still seeing problems?
