### ISSUE TITLE
Getting error when trying to add license

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#321]
Good morning!

We're getting an error every time we try to add a license. It pops up right when you hit the "+ add new license" on any user. The error is below. Thanks!

![image](https://f.cloud.github.com/assets/4027030/2294754/70508940-a086-11e3-9e43-762069ec49d1.png)

**Comment by daviddurand** [comment]
Thanks for the report. This is fixed now.
