### ISSUE TITLE
Users with pending activation not able to set password

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#324]
We have several new users that were manually added to aga53756.tizrapublisher.com this morning and set to pending activation. When they enter their email address and hit login, they get sent to this URL https://secure.agilepdf.com/login/31a3hm/internal in IE with a page not found error or to https://secure.agilepdf.com/login/31a3hm/tempredirect in FF and Chrome with a blank page. 

You can use cknjj@yahoo.com as a test account, I've verified the account is set up correctly for a pending activation user.

Please fix asap, we have a customer who is waiting to give 10 students access to the site to study for exams.

**Comment by daviddurand** [comment]
Sorry about this.

There is indeed a problem with the redirection to the registration form for accounts like this.

We will fix it tonight, but we do not want the user impact of a restart at this time, and there is an easy workaround -- simply click on the register link directly, and fill in the form.

If you add some text to the login dialog telling new folks to do that, you should be able to work around the support issues for the rest of today.

**Comment by daviddurand** [comment]
I reset the account back to pending after completing my test.
