### ISSUE TITLE
Email Verification Required status in email

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#33]
ASPPA email that I just sent, came through like this: Email Verification Reqired

"Required" is spelled incorrectly.
I used ${status} to show status.

**Comment by daviddurand** [comment]
oops.

fix in place shortly. Won't take effect before tonight, however.

---

David G. Durand
CEO / CTO
Tizra
9 Catalpa Road
Providence, RI 02906

Email: david.durand@tizra.com
Phone: +1 401 935-5317
FAX: +1 401 273-5171
Web: http://www.tizra.com/
Blog: http://blog.tizra.com/

Online publishing unbound.

On Thu, Feb 23, 2012 at 11:14 AM, Ryan Hood
reply@reply.github.com
wrote:

> Email Verification Reqired

**Comment by ghost** [comment]
Thank you.
