### ISSUE TITLE
Upload Progress Bar Broken in Safari & Chrome

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#331]
In Chrome 33.0.1750.152 and Safari 7.0.2 for Mac, the progress bar does not progress when uploading a PDF.  In Chrome, you just see "Operation started" until the upload completes.  In Safari, the file selection dialog stays in place till the upload completes.

Firefox 26.0 seems to work fine.

**Comment by adane** [comment]
This doesn't seem to be a JavaScript caching issue.  Tested in Chrome under another user account in my Mac.

**Comment by daviddurand** [comment]
I've never been able to reproduce this, and now it's apparently working for you again.
