### ISSUE TITLE
On short PDFs (2-5 pages tested), the last page's Bookmark does not upload/display into Tizra TOC

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#333]
I created 2-page and 5-page PDFs and bookmarked each page. Clicking on the Bookmarks in Acrobat brought me to the appropriate pages. After uploading the PDFs to Tizra, the LAST page's bookmark (so, on p. 2 or on p. 5) did not display in the Tizra Table of Contents. 

If I added a new page to the PDF in Acrobat, and then uploaded that PDF into Tizra, THEN the final page's bookmark would display (but any bookmark added to the new final page -- p. 3 or p. 6 -- still would not display).

SAMPLES in https://secure.agilepdf.com/admin/1qje1l/main
Document with 2 pages and no bookmark displaying for second page: 
00 - NO BOOKMARK PAGE 2

Document with newly inserted third page and bookmark displaying for second page, but not third page:
00 NEW PAGE INSERTED -- BOOKMARK DISPLAYS P. 2 BUT NOT P. 3

**Comment by daviddurand** [comment]
I can't replicate this, and am closing as it's very old.
