### ISSUE TITLE
Trouble making a purchase on the TRB HCM site

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#335]
This person is unable to make a purchase. I got as much information as I could but It doesn't look like they are seeing the error code that would tell us specifically what's wrong. This is my correspondence with them (newest first):

Hi David

Please see screenshot below. I have checked my card details and we definitely have money in the card to pay TRB. However I doesn't work. I have tried with different card too. 

http://screencast.com/t/RycZzGYu

---

On Mon, Apr 7, 2014 at 4:45 PM, dfranks wrote:

I'm sorry for the trouble. Are you seeing any other information about the problem that may be helpful? 

Are you able to send me a screen capture of the error you are seeing?

---

Date: Mon, 7 Apr 2014 02:43:38 -0700
Subject: Technical Support [488]

Name: Balakumar Arumugham
Email: bala@dce.ie
Phone Number: (974) 700-3305
What web browser are you using? 
IMPORTANT: Make sure to include the version.: Google Chrome Version 33.0.1750.154 m
What version of Acrobat Reader do you have?: Pick a version
What file or page were you trying to access? Provide URL if possible.: https://secure.agilepdf.com/commerce/1a8l53/fulfiller_paypalpro?__utma=1.1327750316.1396857155.1396857155.1396857155.1&__utmb=1.48.8.1396858303037&__utmc=1&__utmx=-&__utmz=1.1396857155.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provid
What were you trying to do when you got the error?: Make payment for online access of HCM 2010 guidelines
What did you see in place of the content you expected?: Payment cannot be processed
Describe in further detail what site error you are experiencing so we can help fix it.: I am trying to purchasing online access for HCM 2010 guidelines for our office based at Doha, Qatar. However I couldn't make a payment. I am using my office credit card from Commercial Bank, Doha, Qatar. Could you please assist me as we need to sort this out asap. Thanks.

**Comment by adane** [comment]
Test transactions are going through OK.  Are you able to reproduce this issue?

**Comment by daviddurand** [comment]
I saw this in the logs, and paypal isn't giving us a specific error (the
stupid message after the colon is actually the message the credit card
processor sent us.

It's almost certainly a problem with the card or some other aspect of the
transaction. I notice that these non-specific errors are much more common
with international cards.

I don't know if Quatar presents problems in that way. If there's another
way for TRB to accept payment, creating the license by hand may be easier….

---

David G. Durand
CEO / CTO
Tizra
9 Catalpa Road
Providence, RI 02906

Email: david.durand@tizra.com
Phone: +1 401 935-5317
FAX: +1 401 273-5171
Web: http://www.tizra.com/
Blog: http://blog.tizra.com/

Online publishing unbound.

**Comment by orangedrink** [comment]
Ok. Thanks guys!
