### ISSUE TITLE
PDF source view is going to document TOC page in Firefox

### ISSUE THREAD

**Issue by aabercrombie** [Tizra/Tizra-Customer-Tracker#336]
This seems to be happening on one specific event for one specific site, but we haven't changed anything so I don't know why this is happening.

Their conference is tomorrow, so this needs to be addressed ASAP!

For http://knowledgecenter.clemetrobar.org (cmba.tizrapublisher.com), for the collection 14th Annual Northern Ohio Labor & Employment Law Conference, when you click on the download button, instead of the ~~PdfSource/0 link opening the PDF in a new tab for download, it opens a new tab with the document TOC page. When you click on the link for the PDF, it opens in the same window, and repeat in a loop. You can never actually download the paper. From the screenshot you can see this is going to the ~~PdfSource/0 link, it's just not opening the pdf.

Ideas? Help?

**Comment by aabercrombie** [comment]
Oh, one other note, this doesn't happen when I'm signed in as an admin. Only when I'm signed in as a user. You can use aabercrombie@omnipress.com/encore to log in to see this if needed.

Here's a screenshot. http://screencast.com/t/3C3rQetBwtx
Here's a screenshot. http://screencast.com/t/3C3rQetBwtx

**Comment by adane** [comment]
One quick thing to check: Does the user account you're testing with have a license to view PDF source?  This is not turned on by default, since it's a special option we set up for you guys.

**Comment by daviddurand** [comment]
Abe was right, and my email was incorrect (I hadn't yet checked github, so I didn't realize the access control angle...).

I checked, and I have found the problem. The s14labor group had source downloads turned off. I think that there's a problem with download checking where it is picking one of the licenses before checking that the particular view is allowed. This means that with multiple licenses with different access to attachments and source downloads, not all of the licenses would be checked, just the first one.

I changed the access on that group, and things are now working for the site. I'll work on a fix for the collision between the different license checks, but for the time being you should be good.

  -- David

**Comment by aabercrombie** [comment]
Looks good for now. Thanks guys!
