### ISSUE TITLE
Free Attachment heading displays in sidebar when no Free Attachments are Visible

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#339]
See attached.  The document at...

http://abedemo.tizrapublisher.com/5lg5kh/

...has a single Free Attachment published, with "Is Visible" unchecked.

![screenshot 5 8 14 11 19 am](https://cloud.githubusercontent.com/assets/1355614/2917314/9817b966-d6c4-11e3-97ed-a7eb6a1c2a4e.png)

**Comment by daviddurand** [comment]
closing ancient/fixed bugs
