### ISSUE TITLE
Excerpt created after document is tagged are inheriting tags, but not displaying them

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#341]
I create a new Document
I tag the Document
I create Excerpts.
Tags do not display on the Excerpt Properties screen, but the Tags are definitely inherited, as the Excerpts appear in lists filtered on the tag and the Excerpts appear in Collections matching on the tag (see attached image).

WORKAROUND: Manually add the tag on the Excerpt Properties screen OR use the Super Tagger to add the tags in bulk.

![tags not displaying on excerpts](https://cloud.githubusercontent.com/assets/2480073/2919979/4627f5fe-d6e1-11e3-87e2-c9013e778f1b.png)

**Comment by daviddurand** [comment]
Closed, referred back to #136
