### ISSUE TITLE
Accessibility Tags and Logical Page Numbering is being removed from excerpt-based PDFs

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#342]
It sounds like the process of generating PDFs from Excerpts may be stripping data out of the PDFs that it would be preferable to leave in.  For example, this download from the CUPOLA site...

http://cupola.columbia.edu/5scjl2.pdf

...no longer has the logical page numbering info that is in the source file.

In addition, ARL has commented that accessibility tags added to their PDFs are no longer visible when they download excerpt generated versions.

**Comment by adane** [comment]
ARL provides the following example of a PDF download that has lost its accessibility tagging...

http://publications.arl.org/4bnfv1.pdf

Comments from Kaylyn:

That's RLI 283, found here http://publications.arl.org/rli283/

When I uploaded it, the PDF included bookmarks and some metadata (title, author, keywords, copyright info, language). Those elements are all absent from the uploaded version. 

On the plus side, the logo images that I tagged as artifacts are still tagged that way in the uploaded version.

**Comment by adane** [comment]
Further information from ARL.  Referenced files sent by email...

RLI 282 is a good example with tagged figures. The RLI 282 rev2.pdf file is the one that was uploaded to Tizra. The 3p34ja-2.pdf file is the one I just downloaded from Tizra. Open them side-by-side, click on the Order icon (fifth icon on the left that looks like a zig-zag arrow), and scroll through the file. In the uploaded file you can see the Figure and Table tags. Those aren't in the downloaded file. Neither are the bookmarks.

Open File Properties for both. Click on the Description tab in the uploaded file and you will see author, title, keywords, etc. That is missing in the downloaded file. Click on the Advanced tab in the uploaded file and you will see that the Language is English. That is missing from the downloaded file.

**Comment by daviddurand** [comment]
We are currently working on a variety of accessibility issues in connection with implementing screen reading. Much of the critical accessibility tag information is not stored on the PDF page, but as a global structure associated with the entire document, and linked to each page.

This makes extracting that information considerably more complicated when chopping up a PDF.

We will follow up here once we know what the timing will be on addressing this issue.

**Comment by daviddurand** [comment]
Logical page numbering, like reading order information, is also stored as a file level property. Unlike the reading order information, this is stored in the form of instructions about how to generate page numbers for the file, presenting similar issues when extracting from a PDF (as those instructions need to be edited to reflect the new size of the file.

Again we will follow up once we have an ETA on this.

**Comment by daviddurand** [comment]
We are working on a number of accessibility improvements, including integration with a screen reading vendor. As part of that process, we are revisiting text extraction and PDF processing generally.

As part of that process, we are investigating the issue of logical page numbers and the accessibility information stored in the PDFs.

While it's tricky to extract and merge this information, we believe that it should be possible.

**Comment by daviddurand** [comment]
This is a limitation of Excerpts. If such features are needed, multiple PDF sources should be used for the document, and those downloaded, rather than relying on Excerpts.
