### ISSUE TITLE
Drop shadow in HW PDF not rendering properly

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#344]
This page in Tizra: http://hw-content-review.tizrapublisher.com/mama-doc-medicine/40
has a white and grey drop shadow where it should only be grey.

The .pdf with the desired grey drop shadow is here: http://hw-content-review.tizrapublisher.com/mama-doc-medicine/40.pdf

The .pdf in the jpedal viewer has a much darker drop shadow (different from the Tizra server's redering). Screen shot attached.
![mama-doc-medicine-40_page in jpedal](https://cloud.githubusercontent.com/assets/2480073/3220995/612d9046-f006-11e3-91db-e848cfb0f0be.png)

**Comment by cbwinchild** [comment]
Ran "flatten overprints and transparencies" PDF fixup and resolved; 
Alerted jpedal via idrsolutions: case 17427 bug report.

**Comment by daviddurand** [comment]
cbwinchild I believe this should have been fixed by the latest jpedal. Closing, but can you validate with the original unflattened file. If still a problem, reopen.

**Comment by cbwinchild** [comment]
David, thank you! This was one of my 1st jpedal reports and it never made it into my spreadsheet for tracking. IT'S ALL FIXED. I'll let HW know and thanks again for follow-up.
