### ISSUE TITLE
Admin Progress Bars Not Working Properly

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#348]
In Chrome and Firefox, when a document is uploaded, the progress bar comes up but stays at 0% until the upload completes.  In Safari, no progress bar comes up...the upload dialog stays visible until the upload completes.

Progress bar does not update on document publish.

**Comment by daviddurand** [comment]
Fix will go into effect this evening.

**Comment by adane** [comment]
Looks good in Chrome and Firefox, but upload progress bar is still not working in Safari.  Publish progress bar does work in Safari.
