### ISSUE TITLE
ASPPA License Problem

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#35]
In IE, the calendar isn't showing up when I try to create a license with a fixed date range.

ASPPA uses IE for internal uses and needs the calendar to work for them.

**Comment by adane** [comment]
I'm afraid MSIE is not supported for Admin Interfaces.  

It used to be we supported only Firefox, as indicated in the warning messages that pop up when you log into the admin, but we have broadened somewhat to include Chrome and Safari.  IE still causes problems, though.  In fact, you may find that it actually causes bad data to be entered in some places.

**Comment by ghost** [comment]
So what do you tell a customer that isn't allowed to download any other browser?

Is there any way that you can just fix the calendar problem? That is the only thing they are currently using.

**Comment by adane** [comment]
We can add it to the backlog.  Let us know how you'd like it prioritized.

**Comment by ghost** [comment]
Is there any way to see if using chrome frame for IE would fix this without investing a large amount of David's time?

**Comment by ghost** [comment]
chrome frame just for the backend though... I know we are still using ie7 compatibility mode for the front end, and the two things can't exist together.

**Comment by adane** [comment]
We can look into it after we get the static export work delivered later this week.
