### ISSUE TITLE
Multiple Pages Displaying in Content Reader

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#352]
Pages on esc4's site are displaying with double and triple pages. Page examples: 
http://r4hub.esc4.net/49vgf1/90
http://r4hub.esc4.net/5t64ke/27

Happens in any browser. Does not happen in jpedal or on support.tizra.com site.

**Comment by daviddurand** [comment]
This was a CSS problem related to readspeaker preliminary deployment.

Fixed by 2613acdc3407d21e99a068bfe1a9ae4205c8de28
