### ISSUE TITLE
Editing Email Templates

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#354]
I'm trying to edit "mail.activatedaccount" email template, but every time I click save it reverts to the previous version.

How can I make a change and retain it?

**Comment by cbwinchild** [comment]
Hi Ryan,

Sorry for the delayed response. I got in there to do some testing and it looks like there is a bug. I'll go ahead and report the specifics.

Thanks for your patience/Catherine

**Comment by ghost** [comment]
Thanks. 
Do you know how long it will take to fix this bug? Tizra's support email is in the email along with a broken link, so I would like to get this fixed asap.

**Comment by ghost** [comment]
Are there any plans to get this bug fixed? I haven't heard anything for over a month now.

**Comment by daviddurand** [comment]
This is fixed.
