### ISSUE TITLE
Contact and Email Information Page Not Saving Newly Selected Templates + Access Bug

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#355]
On SETTINGS > Contact and Email Information Page, when I select any template in the Email Template field, after changes are made and I Save, the system reverts back to the "Pick an email template" option and no changes are made to the template. This was also reported in #354 

Additionally I cannot access the SETTINGS > Contact and Email Information Page on cbw-sandbox.tizrapublisher.com and instead get the following error message:
Template error on operation view Method "public java.lang.String com.cubchicken.contactus.model.SiteContactInfo.getDisplayName(java.lang.String)" threw an exception when invoked on com.cubchicken.contactus.model.SiteContactInfo object "com.cubchicken.contactus.model.SiteContactInfo@4a3609b1". See cause exception. The failing instruction (print stack trace for 3 more): ==> ${contactInfo.getDisplayName(property... [in template "com/cubchicken/admin/metaTypes/sitedisplay/contactinfo.ftl" at line 106, column 70]

**Comment by daviddurand** [comment]
This is now fixed
