### ISSUE TITLE
delete license email -- fyi

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#36]
Default message. First sentence is a little off... "${site.hostname} has has a"

<p>Your account at ${site.hostname} has has a subscription to
"${product}" removed. If you want to see the details of your current subscriptions,
go to ${site.homepage}/~userOrderHistory and log into
your account.
</p>

**Comment by daviddurand** [comment]
Thanks... and it should be past tense, as well. Changing 'has has' to 'had'.
should be live tomorrow.
