### ISSUE TITLE
Error on Saving ToC Changes in Multi-PDF Document

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#360]
Confirmed the following report from WFU:

I was trying to save some changes in the Table of Contents for a document called "The Winter Sleep of Captain Lemass" and I keep getting an error. Specifically, I was changing the name of the Full Cover from "Dust Jacket" to "Full Cover" and it won't let me save that change.

![screengrab93014](https://cloud.githubusercontent.com/assets/1355614/4461444/5a1ef9e0-48ba-11e4-988e-f2ebfa75ddec.png)

**Comment by daviddurand** [comment]
closing ancient/fixed bugs
