### ISSUE TITLE
Issue when uploading power points

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#363]
When we upload a power point attachment everything goes fine until you try to download it. When you click on it to download it sends us to an AgilePublisher page that says Internal Server Error. Only seems to be happening with power points we upload now. Ones that have already been uploaded work fine! Other file types are working fine!

**Comment by adane** [comment]
Hi Kuhrt--

Are you still seeing this issue?  Have you tried making sure that the mime type is set to PowerPoint?  (See attached.)

Please let us know if you're still seeing problems.

Abe

![screenshot 12 30 14 11 42 am](https://cloud.githubusercontent.com/assets/1355614/5580468/02c77bee-9019-11e4-9645-83f9c9ce7c2d.png)

**Comment by Kuhrt** [comment]
No! It started working a while back I can't even remember when! Thanks so much!

Kuhrt Cowan
806.241.7788
Sent from my iPhone

On Dec 30, 2014, at 10:44 AM, Abe Dane <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Kuhrt--

Are you still seeing this issue? Have you tried making sure that the mime type is set to PowerPoint? (See attached.)

Please let us know if you're still seeing problems.

Abe

[screenshot 12 30 14 11 42 am]https://cloud.githubusercontent.com/assets/1355614/5580468/02c77bee-9019-11e4-9645-83f9c9ce7c2d.png
