### ISSUE TITLE
Admin cannot access Static Page on Orca Site; receive error message

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#364]
When trying to access Static Page "Text2Reader" (custom URL = text-2-reader) on Orca site -- http://digital.orcabook.com/ -- receive the following error message (both as Admin and SU):

Template error on operation view get(isOverride) failed on instance of com.cubchicken.cms.model.MetaTagDefinition. See cause exception. The failing instruction (print stack trace for 10 more): ==> #if tagDef.isOverride [in template "com/cubchicken/admin/adminCommonMacros.ftl" in macro "adminPropertyListing" at line 235, column 41]

**Comment by daviddurand** [comment]
fixed
