### ISSUE TITLE
PDF download not working on android phone

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#366]
OEM Press customer unable to download a PDF on a Note 4; Android phone. I confirmed that customer has a license to the download. The customer CAN view the book online, but gets message that the downloadable PDF file is "not available" when he tries on his phone.

The content is part of the "MRO Package" collection, to which customer has a license -- http://digital.oempress.com/The_Medical_Review_Officers_Manual_4th_Edition1/

I was able to successfully download on Windows 8.1, in IE  (11.0.9600.17416), Firefox and Chrome.

Just in case it's helpful, this is an error seen when trying to download same PDF on a Windows 7; IE Version 9.0.8112.16421 machine, before finally being able to download successfully.

"C:\Users\curtis\AppData\Local\Temp\Z4TdwbQk.pdf.part could not be saved, because the source file could not be read. 
Try again later, or contact the server administrator."

**Comment by cbwinchild** [comment]
Quick follow up/FYI...another end-user (for the same Tizra publisher, above) had an issue on their Android phone, specifically, Document was not displaying correctly (screen shot attached here). End-user was able to view the Document successfully on their desktop.
![screenshot_2014-12-19-14-20-42](https://cloud.githubusercontent.com/assets/2480073/5526735/cf2803b2-89c4-11e4-8837-1f99e22408e8.png)

**Comment by daviddurand** [comment]
closing ancient, now fixed, bugs
