### ISSUE TITLE
ASPPA eLibrary Concurrent Login issue

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#37]
Hello, I was double checking the concurrent user limitations today, and noticed that it doesn't seem to be working.

I set up rhood@omnipress.com with access to the ERISA Outline Book for a set date range, and 2 concurrent users. I'm currently logged into the site with 5 computers. Please let us know if there is a setup problem, or if there is a bug with the concurrent user limitation settings. The current password for the above account is test.

Let me know if there is anything you need me to do.

Thank you.

**Comment by adane** [comment]
I'll check into it right away.  What is the URL for the site you found the problem on?

**Comment by ghost** [comment]
http://elibrary.asppa.org/

Thank you.

**Comment by adane** [comment]
Seems to be working normally.  Here's how I tested:

1) Created non-admin account with license for the ERISA Outline Book collection.
2) Set concurrent access limitation in the license to 1
3) Went to a different browser and logged in on this page...

http://elibrary.asppa.org/erisa-outline-book-chapter-1a/1

Result: Access successful.

4) Went to another browser and logged in on this page...

http://elibrary.asppa.org/erisa-outline-book-chapter-1b/5

Result: Access Denied

5) Went back to the license and increased the concurrent access limitations to 2.
6) Retried access in the second browser.  Result: Access Successful.
7) Went to a third browser and logged into this page...

http://elibrary.asppa.org/erisa-outline-book-chapter-1b/6

Result: Access Unsuccessful.

Maybe some of your test browsers are still logged into multiple accounts, including some admin accounts?

**Comment by ghost** [comment]
Thank you Abe. I think this is a result of a poor understanding of the concurrent license settings, but I think with your explanation of what you did I know understand it better.

**Comment by ghost** [comment]
Abe, Is there a "Access Denied" message macro I can use for concurrent user limitations met? 
It would be helpful for us to be able to include a message that says that the max number of users are currently using the publication and that they should buy more users.

Thanks.

**Comment by adane** [comment]
As far as the system is concerned, the reason the user has been denied access is that they have a license, but not one that covers the particular access they are attempting, so you can use the following macros to display a message.  

%IF_CONTEXT_VALUE_BEGIN(DENIED_REASON,3)%
Your message here.
%IF_CONTEXT_VALUE_END%

Note that this message will be displayed to anyone who tries to access a page with licenses that apply to something else (a different book, for example.)

With a small amount of custom work, we can develop the ability for you to display a message that ONLY appears when the reason access is denied is that the concurrent session limit has been exceeded.  Let me know if you'd like us to look into that.

**Comment by orangedrink** [comment]
Thanks Abe. We're getting flooded with support requests from users who are being confused by this. Could you send us an estimate for doing this work? Let me know if you need any other information.

**Comment by adane** [comment]
We'll get back to you ASAP.

**Comment by orangedrink** [comment]
OK. Thanks

**Comment by adane** [comment]
OK, I've discussed with Dave D. and it would be 4-5 hours, so $800-$1000.  Let us know if you'd like us to go ahead.

**Comment by orangedrink** [comment]
Please proceed. Any idea how many days before we can expect that?

**Comment by ghost** [comment]
Any progress on this?

**Comment by daviddurand** [comment]
I've been working on another project (and catching up on some things after the long haul on the export feature), but I hope to be starting this by the end of today. My best guess right now is that it will be live by Thursday if I can start by then. There's a definitely a little variability there -- as this is the first time that we'll be reporting on specific licenses _contributing_ to an access denied condition -- All of the other causes (not logged in, no valid license found) were results of the whole check -- now we will be accumulating an "explanation" of things tried that did not work -- to be displayed only if none of the available licenses actually grant access.

We've got a framework that should make this possible, but it is the first time. I'll take the quickest route to a supportable solution.

Sorry for not updating you sooner on this.

**Comment by SeanLawler** [comment]
Do you think this will be complete prior to the sprint you'd like to start on Monday?  This is a pretty high priority.  Thanks.

**Comment by daviddurand** [comment]
Yep, that's the plan. It took a bit longer to clear the decks than I had planned.

**Comment by daviddurand** [comment]
A new feature is in place.

The markup is generated by the the "access denied message" block that appears on access denied pages.

If access was denied due to a concurrent access limitation failure, markup like the following is included before the list of offers.

<ul class="t-denied t-license-details" >
   <li><span class="t-denied-message">Concurrency limit Exceeded on license.</span>         <span class="t-denied-limit">Limit is some_number</span>
       <span class="t-denied-object"> simultaneous accesses to "Some_object_name"</span>
   </li>
</ul>


There may be more than one license in play, at least on some sites with complex access control.

We don't currently track other reasons a license might not grant access (expiration, etc), but we may at some future point in time.

You may need to reconfigure the stylesheet to display this stuff (and certainly to format it).

**Comment by orangedrink** [comment]
Thanks for your hard work on this David.

We currently use a free HTML block with %IF_CONTEXT_VALUE_BEGIN(DENIED_REASON,0)% type macros to display error messages on the access denied page and would like to continue doing so if possible. Do you think there is any possibility of adding an ACCESS_DENIED code we can access via a macro? 

Using this access denied message block there will be no way to customize the message (to remove the erroneous capitalization of he word exceeded for example ;) ) and no way to show only this error message without showing the error message associated with DENIED_REASON 3

If you can come up with an alternative to using the DENIED_REASON codes then I'm ok with that as long as it works well.

Thanks again.

**Comment by daviddurand** [comment]
I think you can hide all of the access code messages from the access denied block, and just keep the new one. You should be able to change the text with CSS, as well.

That said, I'm going to add a new DENIED_REASON value: 10, but that will lose information, as the new setup gives a list of license failures. Right now it only includes the concurrency failures but over time, it will include expirations, etc.

You'll get 10 if _any_ of the reasons was a concurrency problem. Look for it tomorrow.

**Comment by adane** [comment]
OK, this is all set.  You can now use a macro something like the following to display your message.

%IF_CONTEXT_VALUE_BEGIN(DENIED_REASON,10)%

<div class="error">
<p>The maximum number of simultaneous user sessions permitted for your account has been exceeded.</p>
</div>

%IF_CONTEXT_VALUE_END%
