### ISSUE TITLE
New Collection not being added to search

### ISSUE THREAD

**Issue by PStokesOmni** [Tizra/Tizra-Customer-Tracker#371]
I added a new collection to the http://library.smrp.org/ site, Track 6.
I followed the examples of the other collections but foe some reason I cannot get the Track 6 to display on the advance search dropdown.

**Comment by adane** [comment]
Hi Paul--

It's showing up OK for me...it's at the top of the list (see attached).  Maybe it just took a little while to appear?

![screenshot 12 31 14 10 57 am](https://cloud.githubusercontent.com/assets/1355614/5588659/d8befa5c-90db-11e4-9140-ddd4c24ae863.png)

**Comment by PStokesOmni** [comment]
Strange because I do not see that at all. I will check on Friday to verify
