### ISSUE TITLE
Edit Properties screen opens and displays at the bottom of the content screen

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#373]
![edit-properties-screen-bug](https://cloud.githubusercontent.com/assets/2480073/5843800/190558c0-a17d-11e4-8919-0690e0046758.jpg)

On any content properties screen, if I  click the [edit] link next to a property, the Editing Property screen opens below the displayed properties screen. (screen shot)

(The Add New Properties screen opens correctly when I click the +New Property link.)

**Comment by daviddurand** [comment]
I can't see this, either on your site, or my test site.

Have you tried clearing your cache or doing a forced refresh a couple of times?

What browser are you using?

**Comment by cbwinchild** [comment]
I was in Chrome. cleared cache. all better. sorry for false alarm!

On Wed, Jan 21, 2015 at 3:25 PM, David G. Durand notifications@github.com
wrote:

> I can't see this, either on your site, or my test site.
> 
> Have you tried clearing your cache or doing a forced refresh a couple of
> times?
> 
> What browser are you using?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Tizra/Tizra-Customer-Tracker/issues/373#issuecomment-70914674
> .

## 

Catherine B. Winchild
Technical Writer & Trainer
Office Hours: M-F 10:30am - 2:30pm EST

Tizra, Inc.
9 Catalpa Rd.
Providence, RI 02906
