### ISSUE TITLE
User Accounts Not Showing Up in Users Included in Account Set list

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#377]
I add User Tag to Individual User; 
User is included Account Set.
Account Set to which they now belong shows up on the Individual's Account page.
But when I go into the Account Set, the User is not listed at the bottom of the screen in the Accounts Included in Set list.

NOTE: Access to the licensed content associated with the Account Set is STILL granted.

**Comment by daviddurand** [comment]
fix is on the way, but reindexing will need to complete overnight.
This bug did not affect actual membership, or access control, but only display and data entry in admin tools.
