### ISSUE TITLE
Customer can't get to site

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#378]
Good morning!

I have a customer who can't see the site from their school district. I've spoken with their IT to make sure everything was unblocked correctly and it is but they wanted me to check and see if their ip had been blacklisted from our site. I couldn't find anything from here but I wanted to check with y'all to see if this was a possibility. Their ip is 66.76.19.5. When doing a blacklist lookup, they are on a few spam blacklists and don't know if that matters for us. I just wanted to ask to see if they were being specifically blocked. If y'all could let me know any information that'd be great! Thanks!

**Comment by daviddurand** [comment]
There's no blocking going on at our end. There may be a firewall configuration at their end (if they really can't even get to the site). More common are firewalls that block secure.agilepdf.com (needed for HTTPS to our access control), or that strip cookies (needed for login session management).

We are hosted on AWS, which should not be a problem, but is occasionally targeted by zealous firewalls. But this is much more unlikely, and would again, only be relevant if they can't get any response from Tizra at all..

**Comment by Kuhrt** [comment]
Thank you so much for the reply! I'll let them know!
