### ISSUE TITLE
Maximum number of pages exceeded?

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#380]
Just this afternoon I tried to update one of our files that we have and got this error below.

![image](https://cloud.githubusercontent.com/assets/4027030/6971363/a8ad8b2c-d941-11e4-9119-cb8dd95de157.png)

It says we have 332 million pages all of a sudden and won't let us revise any of our current files. Also, some of our files aren't displaying from what I'm assuming is the same error. Found out about this just now. I'm not sure what happened from this morning to this afternoon, any help would be great! Thanks!

**Comment by daviddurand** [comment]
The bad page count has been fixed...

If you are having trouble with particular documents, please let me know.

The bad page count wasa result of some maintenance to make sure that
documents are not affected by a recently fixed bug. If you are having a
problem I'd like to check what's going on...

---

David G. Durand
CEO / CTO
Tizra
9 Catalpa Road
Providence, RI 02906

Email: david.durand@tizra.com
Phone: +1 401 935-5317
FAX: +1 401 273-5171
Web: http://www.tizra.com/
Blog: http://blog.tizra.com/

Online publishing unbound.

**Comment by Kuhrt** [comment]
You're the man! That got it, I can upload now!

I am still having trouble with some documents but it seems to only be from one collection. Here's the link to what it's doing:
http://ccfcs.tizrapublisher.com/fcs_cert_res then click on the "Services for Older Adults Reference Book" link

Most of them on that page are doing it. Instead of pulling up the actual document, it just keeps pulling up the table of contents for it. I've tried saving and re-publishing the files but still can't get it to go. Thanks for checking into this!

**Comment by daviddurand** [comment]
There was a database/calculation conflict in the page count calculation, so
some documents were coming up with more or less random results. In the case
of the fcs_cert_res it was coming out to a really big negative number
sometimes. This  caused the site counts and publish operation to get
confused. Anyway, it seems good now.

---

David G. Durand
CEO / CTO
Tizra
9 Catalpa Road
Providence, RI 02906

Email: david.durand@tizra.com
Phone: +1 401 935-5317
FAX: +1 401 273-5171
Web: http://www.tizra.com/
Blog: http://blog.tizra.com/

Online publishing unbound.

**Comment by Kuhrt** [comment]
Yeah! It's working perfectly! Thanks!
