### ISSUE TITLE
Reader skipping pages

### ISSUE THREAD

**Issue by Kuhrt** [Tizra/Tizra-Customer-Tracker#382]
Now our reader is skipping pages on a collection we have. Here's a link and if you click through you'll see that it just randomly jumps to different pages. Even if you put in the page number you want to go to, it won't. Here's a link to an example so you can see.

http://ccfcs.tizrapublisher.com/serv_old_adu_refbook/1
I think all of them on this page are doing it though:
http://ccfcs.tizrapublisher.com/fcs_cert_res

I tried saving and re-publishing the documents but when I do that, I get this error below and it doesn't finish.
![image](https://cloud.githubusercontent.com/assets/4027030/7011632/744d0c4a-dc70-11e4-978b-606de0c6b5f7.png)

Let me know if there's anything I need to do. Thanks for your help!

**Comment by adane** [comment]
Hi Kurht--

We haven't been able to reproduce the issue you're seeing with the random pages in the reader.  Please let us know if you're still seeing it.

We suspect the Java heap space error is an issue with one of the PDF files in the document (which there are quite a few of).  We're looking at the files and will be in touch.

Abe

**Comment by Kuhrt** [comment]
Yes I am still seeing it. Just tried on my phone, laptop and PC in Chrome, Firefox, IE and Safari and they all do it. I've also received a couple of emails this evening from teachers still experiencing it as well. The link to the book above specifically skips from page 4 to 6, then to 13, then 20, then 39 and so on. It's strange because the thumbnails below show all the pages just fine but when you click on one it takes you to a completely random page and not what you click. What's also strange is the address in the address bar shows the correct order, but the reader shows random pages. Like when it skips from 4 to 6, the address bar says /5 but the reader says 6 out of 329. That's why I thought it needed to be re-processed and published because something got out of whack but I haven't been able to do that. I just tried again and am now getting the error we were getting last week:
![image](https://cloud.githubusercontent.com/assets/4027030/7015777/21169026-dc9f-11e4-9ccc-8de841ebc252.png)
Let me know if I need to do anything! Thanks for all your help on this!

**Comment by adane** [comment]
Thanks for the update, Kuhrt.  This is a very strange one.  We'll continue looking into it.

**Comment by Kuhrt** [comment]
Implemented a fix David sent in an email. Working like a charm! Thanks a ton!

**Comment by adane** [comment]
Hi Kuhrt--

David addressed the issue that was causing problems with multi-PDF Documents last night, so the workaround shouldn't be necessary anymore.

Thanks for your help with this.  Please let us know if you see any further issues.

Abe
