### ISSUE TITLE
Need updated documentation or instructions for "secure referrer" setup

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#383]
All around documentation would be great but specifically I'm looking to set the accepted referer for the NAHRO site at http://nahro53994.tizrapublisher.com/

**Comment by daviddurand** [comment]
It's an additional option so you need to make sure that it's enabled for your site... 

I do not believe that it has changed.

Once it's turned on, there are two advanced site properties that control it (most people only need the second):

**Cross site referral HTTP header** (_siteLinkingHeader_) This is the name of an HTTP header that will be matched to determine if the access will be allowed. This is usually set to "referer" (sic.), as that is the header that a browser sets to indicate the previous page.

**Site linking match pattern** (_siteLinkingUrlPattern_) This is a Java regular expression that must match the value of the relevant header.

you can read about Java's variant of Regular expressions here: 
http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html
unless you are doing complicated matches, any regular expression reference will do.

Once the feature is enabled you will have an option to create a "site linking license" in the admin UI. We recommend making a special user name to hold site linking license(s). The link values show up in the admin UI once at least one site linking license is created. While multiple licenses with different privileges can be used, they will all have the same authentication check.

**Comment by orangedrink** [comment]
Bah.. I was looking at the access control page instead of the advanced settings. Thank you!
