### ISSUE TITLE
freemarker template error on admin login

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#384]
![freemarker error](https://cloud.githubusercontent.com/assets/2480073/7202738/0e00b362-e4e3-11e4-88bb-2120a804ad06.png)

**Comment by Kuhrt** [comment]
We're having the same issue as well. +1

**Comment by cjohnsen2** [comment]
Same.

**Comment by adane** [comment]
Thanks for the reports, all.  We're testing a fix now and will update you as soon as it's in place.

**Comment by adane** [comment]
This issue has been addressed and Admin functions are again available.  Note that there are still some cosmetic issues we're cleaning up, including a list of "Unnamed" items on the Admin homepage.
