### ISSUE TITLE
Unable to delete users

### ISSUE THREAD

**Issue by GWPublisher** [Tizra/Tizra-Customer-Tracker#387]
I received the following error when trying to delete users.
![delete](https://cloud.githubusercontent.com/assets/4049888/7483255/01f36aec-f343-11e4-80de-03405d550831.JPG)

**Comment by GWPublisher** [comment]
Just to update, it does seem like the users are being deleted, but we are still getting the error message.

**Comment by GWPublisher** [comment]
New update, it is no longer deleting users at all.

**Comment by adane** [comment]
Sorry, Tim.  We had our hands full fending off a botnet attack yesterday.  We'll look into this ASAP.  In the meantime, is deleting user licenses a workaround you could use?

**Comment by GWPublisher** [comment]
Thanks for the update, yeah, we can still delete licenses right now.

**Comment by adane** [comment]
Also, David pointed out you can change the Account's status to Cancelled if that's preferable...

http://support.tizra.com/tizra_help_manual_v2-7/247

**Comment by GWPublisher** [comment]
Thanks Abe, we can do that in the meantime.  Is it possible to get a status update on this?

**Comment by GWPublisher** [comment]
One update on our end.  We can delete users, but it first gives an error.  The second time that you try to delete a user, it will delete the user.  Also, if you delete multiple users at once, it will give an error for each user.  So if you want to delete 10 users, it will give you 11 errors, and then it will delete all of them.

**Comment by daviddurand** [comment]
We have a fix coming soon. We'll need to figure out how to schedule it for GW's host. My guess is it may make sense to wait until the semester is over everywhere, but that's up to you...

**Comment by GWPublisher** [comment]
This was fixed with the update.
