### ISSUE TITLE
New fields have appeared on AGA's registration page

### ISSUE THREAD

**Issue by SeanLawler** [Tizra/Tizra-Customer-Tracker#390]
While attempting to create a different bug, I noticed a new checkbox field of "Is free access (disable access control):" with the text listed twice.  I do not think checking this box does anything, but could you remove it and the new text please?  http://screencast.com/t/saiau3NqH

Thanks.

**Comment by cbwinchild** [comment]
Hi Sean,

I set the *Is free access (disable access control) *field's "User editable"
setting to "No." Now it no longer shows up on the agaconferencespot.org's
 User Registration page. (Screen shot, below.)

[image: Inline image 1]

Please let me know if you have any other questions.

Best/Catherine

On Tue, Jul 21, 2015 at 12:58 PM, SeanLawler notifications@github.com
wrote:

> While attempting to create a different bug, I noticed a new checkbox field
> of "Is free access (disable access control):" with the text listed twice. I
> do not think checking this box does anything, but could you remove it and
> the new text please? http://screencast.com/t/saiau3NqH
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Tizra/Tizra-Customer-Tracker/issues/390.

## 

JULY & AUGUST OFFICE HOURS: 5:30 - 8:30 am; All emails responded to within
1 business day.

Catherine Bardagy Winchild
Technical Writer & Trainer

Help documentation: http://support.tizra.com

Tizra, Inc.
9 Catalpa Rd.
Providence, RI 02906

**Comment by SeanLawler** [comment]
Thanks, sorry for the late response, I didn't get notified for some reason.
