### ISSUE TITLE
Error when tying to add a new license to a user on AGA

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#392]
To reproduce log in to the admin interface of AGA and click users, Click any user and then click add license. We're seeing the following error:

Error
Template error on operation view The following has evaluated to null or missing: ==> siteHost.getMetaTypeByName('Offer').localTagDefinitions [in template "com/cubchicken/admin/adminCommonMacros.ftl" at line 1264, column 100] ---- Tip: It's the step after the last dot that caused this error, not those before it. ---- Tip: If the failing expression is known to be legally refer to something that's null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)?? ---- ---- FTL stack trace ("~" means nesting-related): - Failed at: @editLicenseProperties license=licens... [in template "com/cubchicken/admin/adminCommonMacros.ftl" in macro "licenseEditor" at line 1264, column 49] - Reached through: @licenseEditor operationTargetObject=... [in template "com/cubchicken/admin/metaTypes/userdata/addLicenseCreateAddDialog.ftl" at line 15, column 25] - Reached through: #include "/com/cubchicken/admin/metaT... [in template "com/cubchicken/admin/metaTypes/userdata/addLicenseDialog.ftl" at line 4, column 9] - Reached through: #include "/com/cubchicken/admin/metaT... [in template "com/cubchicken/admin/simple_ajaxresponse.ftl" at line 12, column 33] ----

**Comment by daviddurand** [comment]
Thanks for the report... It's now fixed.
