### ISSUE TITLE
secure.agilepdf.com connection untrusted

### ISSUE THREAD

**Issue by ccfcs-ttu** [Tizra/Tizra-Customer-Tracker#396]
When I went to log into our site this morning I was informed that the security certificate for the above expired at 7 AM this morning. I have already received calls from customers regarding this issue. I'm new to this position so I'm not entirely sure this is something on Tizra's end, but I figure you can point me in the right direction if it's not. If it is a Tizra issue is it one that will be resolved shortly?

**Comment by adane** [comment]
Thanks for the report. This is an issue on our end.  We're updating the certificate now.

**Comment by ccfcs-ttu** [comment]
Great! Everything seems to be working now. Thanks!

**Comment by adane** [comment]
Good to know...thanks again!
