### ISSUE TITLE
Account Sets missing

### ISSUE THREAD

**Issue by GWPublisher** [Tizra/Tizra-Customer-Tracker#398]
There is suddenly no list of account sets.  Please help immediately!
![accountset](https://cloud.githubusercontent.com/assets/4049888/11631788/5e7cf5be-9cc9-11e5-979b-05d9447e1235.png)

**Comment by daviddurand** [comment]
This appears to have been a database caching issue with no long-term consequences, and we were able to clear it for you. We will post any updates as we can come up with them. I will leave the issue open, but have removed the bug marker until we can reproduce it and make it an active project. I will post any updates here, when and if I can learn anything more.

**Comment by daviddurand** [comment]
we have removed the check all groups option from the admin UI, making a recurrence of this much less likely.
