### ISSUE TITLE
In Site Browser, Collections should be sorted alphabetically by Name

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#40]
It's difficult to tell what they're sorted by now, but it's definitely not Name, and doesn't appear to be Publication Date.  This makes it difficult to work through Collections systematically.

Offers may have similar sorting issues.  Names of many of them seem to include unsubstituted macros (which are substituted in the main list).

**Comment by daviddurand** [comment]
fixed by 4b9d0448fe44d8faa175588b31900ad482cb8010
