### ISSUE TITLE
Can't publish an offer

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#401]
An offer wasnt showing up for a specific publication on live, but was visible on testing. I unpublished the offer, and went to publish it again on staging/live but it wouldn't let me publish it. Need help getting the offer published and working.

Offer Id:2mo3qg (90967888)
Name of offer: Purchase SMRP Guide to Maintenance Work Sampling

**Comment by cbwinchild** [comment]
Hi Ryan,
You should be able to publish Offer 2mo3qg now. I published successfully twice, but didn't know if you'd want this particular Offer Live _now_, so I left it in your system as unpublished.

I created a new, test Offer, which I was immediately able to publish (I subsequently deleted it). After that, I was able to successfully publish your offer. I'll try and duplicate the issue on my end and report anything wonky, but -- in the meantime -- you should be all set.

Catherine

**Comment by ghost** [comment]
Even with publishing it again, the offer doesn't show up for the publication. http://library.smrp.org/work_sampling/1 -- Only see "No Offers"

Don't know what is preventing this offer from being visible with the publication... we have it poorly setup, or system problem.

Thanks

**Comment by cbwinchild** [comment]
The only thing I can see that looks off is that the Collection on which
this Offer was created -- SMRP Work Sampling -- has no Content listed at
the bottom. So, with no "items within the collection" there are no Offers
to present.

On Fri, Jan 15, 2016 at 1:11 PM, Ryan Hood notifications@github.com wrote:

> Even with publishing it again, the offer doesn't show up for the
> publication. http://library.smrp.org/work_sampling/1 -- Only see "No
> Offers"
> 
> Don't know what is preventing this offer from being visible with the
> publication... we have it poorly setup, or system problem.
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Tizra/Tizra-Customer-Tracker/issues/401#issuecomment-172040083
> .

## 

OFFICE HOURS: 10:30 am - 2:30 pm EST; All emails responded to within 1
business day.

Catherine Bardagy Winchild
Technical Writer & Trainer

Help documentation: http://support.tizra.com

Tizra, Inc.
9 Catalpa Rd.
Providence, RI 02906

**Comment by ghost** [comment]
great, thanks. Never even noticed that.
