### ISSUE TITLE
Transactions failing on INS site

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#403]
![transactionfailerror](https://cloud.githubusercontent.com/assets/2480073/12594535/94b9450e-c444-11e5-8503-a93fa257ebf2.png)
When trying to make a purchase (tested with 2 diff. cc #s) the transaction fails. I've attached a screen shot. The message includes, "Security header is not valid."

INS's has entered all the API information for PayPal Pro in Tizra as of this afternoon. The fulfiller is enabled.

**Comment by adane** [comment]
Looking back at earlier cases of this same error, this usually means the API credentials entered by the customer are not correct.  Can you ask them to double check?

**Comment by adane** [comment]
Issue was caused by an error in the API Password.
