### ISSUE TITLE
Error when deleting Doc/Excpt. from Collection list

### ISSUE THREAD

**Issue by cbwinchild** [Tizra/Tizra-Customer-Tracker#406]
Deletion error if I navigate via the Site Browser to CONTENT > Collections > Documents (or Excerpts) and then select a Document/Excerpt for deletion in the displayed list. Error listed below. 

Note: the Document/Excerpt is deleted successfully, despite the error; Static Pages & Offers delete successfully (no error) when using the same steps. 

![image](https://cloud.githubusercontent.com/assets/2480073/13754463/8ab45926-e9ed-11e5-880e-2f285a65c607.png)

**Comment by daviddurand** [comment]
Fix is not yet deployed. Reopening issue, until fix is in place.
