### ISSUE TITLE
Publishing a collection removes all documents from collection list

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#411]
When I publish a new collection I get the following message: 
No documents have been identified for this collection.

Prior to publishing a collection, I see a list of files that will be associated with it.

**Comment by ghost** [comment]
Before Publishing: http://screencast.com/t/n2UtJusGy
After Publishing: http://screencast.com/t/JPDDf2jZ9

**Comment by daviddurand** [comment]
I believe that this is display bug, and not a problem with the collection -- i.e. if you refresh the display of the collection, by clicking the breadcrumbs or the column browser, the list is displayed correctly.

We'll fix this, but please confirm that this is what you are seeing.
The workaround is just to refresh the display manually for the time being.

**Comment by ghost** [comment]
It seems like things come back but I wasn't really sure how this would impact an actual publish to live. 

Thank you for letting me know it was a display issue only.
