### ISSUE TITLE
Can't navigate to last page of PDF

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#414]
The page controls go to the second to last page but then won't allow me to reach the final page.
http://aga.conferencespot.org/sg1_Sec-II-2016/27

I can't seem to find a setting anywhere that would be causing this.

**Comment by daviddurand** [comment]
Thanks for the report.

I think this a  bug related to a new optional feature in the Tizra Reader -- two-page spread navigation.

I will follow up once there's a patch; should be quite soon.

**Comment by ghost** [comment]
Thank you David

Sent from a mobile device.

On Jul 15, 2016, at 11:13 AM, David G. Durand <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for the report.

I think this a bug related to a new optional feature in the Tizra Reader -- two-page spread navigation.

I will follow up once there's a patch; should be quite soon.

**Comment by daviddurand** [comment]
The fix is deployed now, and confirmed by testing on your example.

**Comment by ghost** [comment]
Thanks. I checked it out too and it looks good.
