### ISSUE TITLE
MyAccount subscriptions list

### ISSUE THREAD

**Issue by ccfcs-ttu** [Tizra/Tizra-Customer-Tracker#416]
Some customer Current Subscriptions in their My Account page aren't listing newest to oldest. They are also listed out of order when looking at their user info as admin. We received a couple of complaints from teachers. They say that everything was fine before the summer break so I'm assuming this is a new issue. I have looked through several other accounts, and while not all accounts have this issue, I quickly found others with the same issue. If you have any ideas what has caused these changes please let me know. I can send a personal email with customer account names if you need examples. Thanks.

**Comment by cbwinchild** [comment]
Hi Derrick, David will likely have much have more insight, but could you post a few user names, so I can see some examples of what you're talking about? Thanks!

**Comment by ccfcs-ttu** [comment]
Catherine,

These accounts have various forms of what I’m talking about.

sharla.anderson@windthorstisd.net
abass@ccisd.net
acollins@cisd.org
adorton@ems-isd.net

**Comment by daviddurand** [comment]
The order of licenses on an account is determined by their "sort value" -- Licenses get their sort value from the offer from which they were created, but it can be edited in the license editor. 

Previously there was no control over the order of licenses at first it was random, then it depended on the order of license creation, but we changed this in 2013...

If users want to check their purchase dates, etc. the Account history block shows all the license-creation transactions in order by date. Most publishers are now sorting their licenses by title, as that makes for a nice display -- a bookshelf page.

**Comment by ccfcs-ttu** [comment]
We want for the licenses to be listed in order of creation, new>old. I have read through the areas in the help manual that sounded like they may be able to accomplish this. Mainly, user sets, which we don't currently use, add a new property that would do this to every collection, and using a cardinal value of 1, 2, 3 etc. during license creation to specify their viewing order. The last of these seems like the simplest option, but to make sure the current years subscriptions list first the sort value numbers would have to be changed for every new and old license when they renew their subscription every year. As far as being able to sort a license by title, or anything else, I haven't been able to find anything. We have collections that we give customers licensed access to, and that is it. It's is a very simple set up. What would be the best/simplest way to make sure licenses list new>old?

**Comment by daviddurand** [comment]
We may be able to treat to get to this as an enhancement. Whether it will be a new block option or a special design property, or what, I'm not sure.

Currently if there is no sort value, licenses are sorted in order of end date, with unclaimed duration licenses showing up last (as they have no end date yet), in order of expiration.

Any change would be to the fallback behavior after the sort value is determined not to exist. Is this still important?

We would actually sort by database ID, but that has the same order as creation date.
