### ISSUE TITLE
Site Browser Breadcrumb & Auto-Scroll Issues

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#419]
When you navigate to an Excerpt list within a Document, clicking the Document's title in the breadcrumb trail no longer takes you up a level to the Document Properties.   

Also, I believe that the site browser used to helpfully auto scroll to put the name of the current item into view.  That no longer seems to be happening.  See attached.

![tizra_publisher_for_demo](https://cloud.githubusercontent.com/assets/1355614/19608971/687ce4f0-97a2-11e6-991c-836accc5c045.png)

**Comment by daviddurand** [comment]
These are fixed now. Recent library updates had impacted the scripts responsible for these features.
