### ISSUE TITLE
Property Name no longer Visible on Property Editing Screen

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#420]
When you click the Edit link next to a Property, the dialog that pops up no longer displays the name of the Property.  See attached.

![tizra_publisher_for_demo 2](https://cloud.githubusercontent.com/assets/1355614/19609443/456a5530-97a5-11e6-92ae-bb72f44a7fc0.png)

**Comment by daviddurand** [comment]
This is now fixed -- it had moved to just after the word "Editing", but is not back in the normal spot.
