### ISSUE TITLE
Bug Creating Master Block from List Block

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#424]
When a master block is created from a list block, at least one setting of the list block is not saved.  To reproduce, configure a list block to Filter by User's licenses, then create a Master Block from it. When you add the Master Block to a layout then disaggregated it, you'll see that the setting on Filter by User's licenses has bee changed to No.

**Comment by daviddurand** [comment]
Fix will be in place after next system restart.
