### ISSUE TITLE
Can't open PowerPoints 

### ISSUE THREAD

**Issue by ccfcs-ttu** [Tizra/Tizra-Customer-Tracker#426]
When trying to open any PowerPoint in Firefox or Google Chrome we are receiving error messages. Internet Explorer seems to work properly. This was first noticed by customers yesterday. Examples of the error messages are below:

Firefox-
Corrupted Content Error
The site at http://ccfcs.tizrapublisher.com/dev_portfolio/~~Attachments/TypesofResumes.pptx has experienced a network protocol violation that cannot be repaired.

The page you are trying to view cannot be shown because an error in the data transmission was detected.

Chrome-
The ccfcs.tizrapublisher.com page isn’t working

ccfcs.tizrapublisher.com sent an invalid response.
ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

Thank you,
Derrick Pedersen

**Comment by daviddurand** [comment]
Thanks for reporting this. The fix is live, and the files are coming down properly.
