### ISSUE TITLE
Spaces in attachment names no longer allowed?

### ISSUE THREAD

**Issue by ccfcs-ttu** [Tizra/Tizra-Customer-Tracker#427]
When clicking to open an attachment that has spaces in its file name, PDF, PPT, etc., the link tries to open as a web page instead of the attachment. Removing the spaces from the attachment names fixes the issue. This was an issue years ago, but it hasn't been an issue over the last couple of years. I have checked older documents that link to attachments with spaces in the name, and they still open properly. Examples of the error messages are below.

Firefix:
Firefox can’t find the file at http://s27691607-preview.tizrapublisher.com/2017_human_growth_bio_adolescents/~~Attachments/Bad URL in source: '~~Attachments/Biological Development Puberty.pptx': Illegal character in path at index 24: ~~Attachments/Biological Development Puberty.pptx.

Chrome:
No webpage was found for the web address: http://s27691607-preview.tizrapublisher.com/2017_human_growth_bio_adolescents/~~Attachments/Bad%20URL%20in%20source:%20%20'~~Attachments/Biological%20Development%20Puberty.pptx':%20Illegal%20character%20in%20path%20at%20index%2024:%20~~Attachments/Biological%20Development%20Puberty.pptx

**Comment by daviddurand** [comment]
Thanks for the report. This is a publishing problem related to an update to link processing that went live last night. A fix will be in place by tomorrow morning, but you'll have to republish once it's in place. The problem does not affect the resources bar in the reader, only the in-document links, so you should have a workaround for any teachers who see the problem today...

I'll close the issue once the change is live.

**Comment by daviddurand** [comment]
This is live now...

**Comment by ccfcs-ttu** [comment]
This appears to be back today.

**Comment by daviddurand** [comment]
Not sure what's happening... I'm not seeing trouble on the page above. Could some books not have been republished after the first fix was made?

**Comment by ccfcs-ttu** [comment]
The ones I noticed this with yesterday are documents that I created yesterday. Everything was uploaded and published yesterday, so it should be good. These are not documents that have gone live yet. These will not go live until June, but I am having to create a new version of everything we have. I am noticing the issue when I check everything in staging to make sure it is correct before it goes live. Today Firefox isn't trying to link to a web page. It doesn't do anything when clicking the links, but you can see a file path line at the bottom of the screen that shows the same "illegal character in path" message. Chrome is giving the same message as above when clicking the links. I even tried republishing the documents this morning, but the issue is still there.

**Comment by daviddurand** [comment]
A change-control merge reverted the fix; new version will actually be deployed tonight.

**Comment by ccfcs-ttu** [comment]
Running into this issue still today.

**Comment by daviddurand** [comment]
Have you got some files that are showing problems thta I can check? looks like you've been rewriting links, but I don't think you should have to...

I want to be sure I'm testing on something that you are actually doing...

**Comment by ccfcs-ttu** [comment]
I have been renaming my files and then re-uploading everything so i don't have to double back later. The following are from a document I just created.

http://s27691607-preview.tizrapublisher.com/2017_college_career_readiness_healthy_living/7?ajax
The "Healthy and Unhealthy Sleep Habits" and "Sleep Hygiene" links.

http://s27691607-preview.tizrapublisher.com/2017_college_career_readiness_healthy_living/16?ajax
The "Drug Testing Information Interview" link.

**Comment by daviddurand** [comment]
It's really deployed now... Sorry for the botched delivery. I just tested with one of your old files.

You could have just left the links in place, and just waited for the republish, but this is of course fine too.

No need any longer, at any rate.
