### ISSUE TITLE
Content loading

### ISSUE THREAD

**Issue by CatharineGray** [Tizra/Tizra-Customer-Tracker#439]
I am trying to load a new product and get the error message below. As a check, I reloaded a file that had already worked successfully. I also logged out and back in again.

![image](https://user-images.githubusercontent.com/33156033/32107207-f15cc858-bafb-11e7-8deb-dc0ee5909a2d.png)
![error message 2017-10-27_9-41-51](https://user-images.githubusercontent.com/33156033/32107258-0f5e1b22-bafc-11e7-842f-a49297ba6244.jpg)

**Comment by daviddurand** [comment]
Thanks for the bug report. This was a temporary problem and was fixed a few days ago... Sorry for not closing this faster. Please re-open if you notice a recurrence.
