### ISSUE TITLE
PDF Doesn't have selectable text

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#44]
Is there any way to allow the ability to select and copy text from the embedded pdf?

**Comment by daviddurand** [comment]
This is something that works when the display is in PDF mode -- but how well may unfortunately depend on the browser plugin and the user's PDF preferences -- it can't work when the page is in image mode.

The full text of the PDF page as extracted from the document is also available in a div that is generated on PDF pages.
You can unhide it, and that can be used for copy and paste regardless of browser and configuration.

**Comment by ghost** [comment]
The extracted text runs together and at times can be fairly unusable, but the text from the PDF is much better typically and I'm trying to offer a better option to our customers.

Obviously I was talking about the PDF mode, not the image mode when I referenced the "embedded pdf" and when you look at the site in a browser other than Chrome (or safari?) the cursor is a hand with an arrow inside it. That cursor doesn't allow you to select any text. But, if I click on the PDF and then click esc, then you can select and copy text out.

I did some further research and it doesn't let me select text because you set all of the PDFs to "Open in Full Screen mode". When I save and embed a pdf with that turned off everything is fine, but when I turn it back on I have the same problem. 
The only thing that I can figure out for this to work is to turn off full screen, but it appears as if IE doesn't recognize the code to hide toolbars the same as other browsers. 

It would be more ideal to turn off full screen mode and allow for people to copy text from the PDF, or improve the text you supply so that it doesn't look like this: formerlywasChapter1intotwo

**Comment by daviddurand** [comment]
The text varies a lot with the PDF that is supplied. Some things come out fine, others get run together (because the PDF does not actually indicate word boundaries, the software must guess them based on the spacing.

There are better PDF text extractors, but they would involve development effort and additional license fees. Let me know if you're interested. Otherwise, we are looking at some updates there at some point, and we'll let you know if we make improvements.

**Comment by daviddurand** [comment]
There have been some recent improvements in the PDF extraction. If you republish documents that were running together, you may see better extracted text now. I am seeing it for some of my old test cases where this was an issue (mostly PDFs produced by TeX).
