### ISSUE TITLE
#, added to all link addresses

### ISSUE THREAD

**Issue by ccfcs-ttu** [Tizra/Tizra-Customer-Tracker#440]
When opening links from documents, every link now has #, added to the end of the address. This is causing JavaScript syntax errors, and other issues, when trying to open various links.

**Comment by adane** [comment]
I had a quick look at a few pages and looks looked OK.  For example...

http://ccfcs.tizrapublisher.com/2017_practicum_culinary_arts_time_management/2

http://ccfcs.tizrapublisher.com/2017_fashion_design_II_completing_job/2

Can you point to a few pages where you're seeing the problem?

**Comment by ccfcs-ttu** [comment]
Sorry, I wasn’t clear enough. The issue only exists when opening web pages. The internal attachments are fine. This being said, all three of the links in the first page you have listed have #, added to their web address when I open them in Firefox or Chrome. As for the syntax error, the second FCCLA link here has it: http://ccfcs.tizrapublisher.com/2017_practicum_human_services_student/6. You must right click, open in new tab, in order to get the syntax error. Other pages give a 404 error. The above is the only example I can directly point you to right now. I have only run into it a few times. It may only be an issue with sites that don’t start with www.*<http://www.*>. I never ran into this issue when opening the above link this way before. The first time I ran into this issue was about a month ago.

**Comment by adane** [comment]
Thanks, Derrick.  This helps.  We're looking into it.

**Comment by daviddurand** [comment]
Thanks for the bug report. We've found the problem.

The issue will close shortly when I push a fix to content management, and will be deployed tomorrow. I'm afraid you'll have to republish the documents that have the stray commas in the FragmentId.

Sorry for the inconvenience.

**Comment by daviddurand** [comment]
Was actually closed by edf038cf928c7275aacc7cf9433df595a93eb6f
