### ISSUE TITLE
Bootstrap Template: Missing Navigation for MultiPage ToCs

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#441]
I just ran across a small issue applying the new bootstrap template to our documentation site.  In the case of very long ToCs like this one...

http://support.tizra.com/tizra_help_manual_v2-9/

...the system breaks the ToC into multiple pages.  The navigation that should appear at the top of the ToC linking among them is missing.  Here's an example of a page with the nav showing...

http://publisher.abc-clio.com/9781851096824/

![american_civil_war__the_definitive_encyclopedia_and_document_collection__6_volumes_](https://user-images.githubusercontent.com/1355614/34011131-fd4893de-e0dc-11e7-8426-b5cf4a956d69.png)

**Comment by adane** [comment]
I went back to the old design on live till we sort this out, so you can find the issue now on staging at...

https://s72899374-preview.tizrapublisher.com/tizra_help_manual_v2-9/

**Comment by adane** [comment]
Just bugging you about this small bug.  Are you getting notifications on this?

**Comment by agriffis** [comment]
@adane Sorry for the late reply. I am getting notifications.

Looks like we introduced a regression... Maybe the test material we were using didn't have multiple pages? Anyway, we'll take a look at getting this fixed.

cc @amygriffis

**Comment by adane** [comment]
No problem, @agriffis !  Yes, quite likely we didn't provide a sample with a long enough ToC for you to even know about the feature.  Would it help if we uploaded a copy of the Tizra manual into your Sandbox?

**Comment by agriffis** [comment]
> Would it help if we uploaded a copy of the Tizra manual into your Sandbox?

@adane Thanks, I think we already have it, just weren't using it as a test case.

**Comment by agriffis** [comment]
We tweaked `Tizra JavaScript.js` to rescue the ToC pager, see https://github.com/Tizra/bootstrap-template/commit/35da361fb1f7376f3d95d6f6a354398383256860

This is now v2.3 in the Tizra Templates area. I wasn't sure whether or how to delete v2.2...

**Comment by adane** [comment]
Thanks, @agriffis.  Tried v2.3 on the support site, but not seeing the ToC pager...

https://s72899374-preview.tizrapublisher.com/tizra_help_manual_v2-9/

(Hid 2.2 by setting the Access Level to 1000)

**Comment by agriffis** [comment]
Sorry @adane, we'd only revealed the pager at the bottom. On second thought it seems important to reveal the pager at the top since it lets the user see what page they're on, so they're both shown now. See https://github.com/Tizra/bootstrap-template/commit/f04ba3ede938d511ae36a350ca479a42acae5ea2

I updated v2.3 in place and applied it to https://s72899374-preview.tizrapublisher.com/tizra_help_manual_v2-9/

**Comment by adane** [comment]
Awesome.  Thanks, @agriffis !
