### ISSUE TITLE
Text Extraction

### ISSUE THREAD

**Issue by jseilga** [Tizra/Tizra-Customer-Tracker#442]
Customers used to be able to select text from the Online Textbook, copy it, and paste it elsewhere for readers, translators, etcetera. Something has changed on the platform that causes the text to copy out without any spaces, rendering the text unusable in these applications.

Example: 
https://www.g-wonlinetextbooks.com/test-pages-mat/1 
 
Text as copy/pasted from left-hand column: 
PhysicalInjuryPhysicalinjuries(cuts,brokenbones,strainedbacks)canresultfromhundredsofdifferentaccidents.Asatechnician,youmustevaluateeveryrepairtech-nique.Decidewhetheraparticularoperationissafeandtakeactionasrequired.Forinstance,ifyouarepullingonahandwrenchashardasyoucanandtheboltwillnotturn,stop!Findanotherwrenchthatislarger.Alargertoolhasmoreleverageandis,therefore,safer.Thisapproachwillhelppreventinjuriesandimproveyourmechanicalabilities.

**Comment by daviddurand** [comment]
This is a consequence of the fact that Chrome is copying the formatted text, which includes markup to position each word on the page individually. We have a fix that will improve the results (by including the spaces), but then every word is on a separate line. The best way to handle this issue, which is a browser issue for many people, is to paste without formatting (Word Paste Special, Plain text option), or use an intermediate editor (like Notepad, or TextEdit in plain text mode) as an intermediate place to paste the content.

Results from some searching:

https://www.makeuseof.com/tag/5-ways-strip-formatting-copy-paste-text/
https://lifehacker.com/5509992/copy-without-formatting-strips-text-formatting-in-google-chrome
