### ISSUE TITLE
Text search issue

### ISSUE THREAD

**Issue by GWPublisher** [Tizra/Tizra-Customer-Tracker#445]
We have been receiving complaints about changes to the search functionality from within the textbook. The Score has been returning as 0% for each result, and seems to be giving numerous results that have little to no relevance to the search text. Are there new functions of the search, or anything we can do to improve the user experience? It seems that users liked the previous experience. It is possible that the results are not being ranked properly, since they all return at 0%.

**Comment by daviddurand** [comment]
This issue was closed because a fix is ready. Deployment to general Tizra will happen tonight. GW's hosting update will need to be scheduled.
