### ISSUE TITLE
Malformed input error.

### ISSUE THREAD

**Issue by ccfcs-ttu** [Tizra/Tizra-Customer-Tracker#447]
Hi guys,

When trying to upload an updated document content PDF Source, I get the following error message "Error: Malformed input or input contains unmappable characters: How to Lower Your Baby’s.pptx". I also get this message if I try to upload the above mentioned PPT into the attachments section. Do you think the apostrophe could be the cause? I'm not having issues with any other uploads. The link is http://ccfcs.tizrapublisher.com/2017_parent_ed_general_prenatal_care/. Also, it doesn't appear that this PPT is linked to in the document. It is just in the attachments section and I get the same message when I try to delete the PPT.

**Comment by daviddurand** [comment]
This is happening because it's a publishing apostrophe (curly quote). A plain straight single-quote should work.

**Comment by ccfcs-ttu** [comment]
Thanks David. I renamed it etc., but it wouldn't let me delete the old file. I had to re-upload the attachments and check the delete old files option. Everything is working now. Thanks, again.

**Comment by daviddurand** [comment]
It may be browser/system combination. I can create files with the character. What I saw on your error is that the character was not being recognized as unicode, which probably means that it was not submitted as UTF-8.
