### ISSUE TITLE
 Tizra favicons displaying insread of G-W

### ISSUE THREAD

**Issue by GWPublisher** [Tizra/Tizra-Customer-Tracker#449]
Tizra logo icons appear in several instances instead of the G-W icon:

- All browsers: PDFs open in a tab 
Examples: 
workbook with form fields:  https://www.g-wonlinetextbooks.com/modern-automotive-technology-workbook-2017/~~Attachments/pdf/ch04.pdf
Instructor resource:  https://www.g-wonlinetextbooks.com/principles-business-marketing-finance-2017-oir-resources/~~Attachments/ch15/ch15_wbanswerkey.pdf

- IE: After a page has been accessed via the reading experience table of contents, next page, premium content, etc.

**Comment by daviddurand** [comment]
This is caused by the fact that the favicon was cutomized in the HTML markup. Attachments don't have the customization and end up with the default (Tizra) favicon.

We are creating a new customization option for your server to change that default.
