### ISSUE TITLE
Reports Area Exporting

### ISSUE THREAD

**Issue by GWPublisher** [Tizra/Tizra-Customer-Tracker#450]
Data dumps not working in Reports; cannot export to either CSV or Excel. (New tab of TIzra window opens instead.) Additionally, “Detailed” Report Format must be selected for Commerce Transactions and Tax Collection. The same error noted above occurs if the Summary option is selected for these items.

**Comment by adane** [comment]
I just tested as follows and was able to generate an Excel '97 report...

1) Under REPORTING > Tizra Publisher Reporting, clicked the button "Export Commerce Data"
2) Selected Excel '97
3) Selected April 8-April 13 as the date range.
4) Clicked "Export"

Result: a file named commerceDataDump.xls was downloaded into my downloads folder containing transaction information for the appropriate period.

Are you seeing something different?  Note that currently only transactions can be downloaded in Excel.

**Comment by GWPublisher** [comment]
Hi Abe,

I tried this again today with settings as close to yous as possible. I still have no download; a new base admin tab opens. I tried a number of combinations in both Firefox and Chrome and receive the same result every time.

**Comment by daviddurand** [comment]
This turned out to be not setting the date range on the export dialog -- it does not inherit date ranges used in the non-downloaded reports.
