### ISSUE TITLE
Unable to log into website.

### ISSUE THREAD

**Issue by ccfcs-ttu** [Tizra/Tizra-Customer-Tracker#451]
I am sure you are already aware of this, but just in case.

When trying to log into website using Firefox we are receiving the following:
Error code: SSL_ERROR_RX_RECORD_TOO_LONG

When trying to log into website using Chrome we are receiving the following:
ERR_SSL_PROTOCOL_ERROR

**Comment by daviddurand** [comment]
We had a big update, and following that a brief regression this morning that caused these bad redirects. This was fixed this morning, as you probably already know. Thanks for the bug report, and our apologies for the disruption.
