### ISSUE TITLE
Tizra Security Certificate issues?

### ISSUE THREAD

**Issue by ccfcs-ttu** [Tizra/Tizra-Customer-Tracker#454]
Both Firefox and Chrome are showing privacy error messages when staff and customers are attempting to access CCFCS Tizra.
![tizra privacy error 8 10 2018](https://user-images.githubusercontent.com/15234243/43980293-40c2f95a-9cb3-11e8-8367-42015c09f20e.JPG)

Please advise.  

Thanks!

**Comment by daviddurand** [comment]
We were fixing a certificate update problem and there was a brief outage during the update. This is working properly again.
