### ISSUE TITLE
In New Chrome Versions, Certain File Uploads are Blocked

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#457]
I receive the attached error when making certain kinds of file uploads from Chrome 69.0.3497.92 for Mac.  

It doesn't seem to occur when creating new Documents.  Only when adding new attachments or document sources to existing documents.

![2018-09-14 03 57 01 pm](https://user-images.githubusercontent.com/1355614/45572421-382d3900-b837-11e8-9c69-690b228e3386.png)

**Comment by agriffis** [comment]
https://www.chromium.org/developers/design-documents/xss-auditor

especially "Debugging via View Source" might be helpful to identify the reflection that's tripping the auditor.

**Comment by daviddurand** [comment]
I suspect this is already fixed in Chrome. Abe could not replicate just now with version `69.0.3497.100`. I'd never seen it at version `69.0.3497.80-something`. Now I'm at `70.0.3538.16` and I'm not seeing it either.

I'm going to close it now and we can re-open later if it happens again

**Comment by adane** [comment]
Ok, I figured out how to make this happen in the current version of Chrome (69.0.3497.100 for me). If you paste a video embed code from Wistia into the Abstract field, like the following...

`<script src="https://fast.wistia.com/embed/medias/d4c8hwxm4h.jsonp" async></script><script src="https://fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><div class="wistia_embed wistia_async_d4c8hwxm4h videoFoam=true" style="height:100%;position:relative;width:100%"><div class="wistia_swatch" style="height:100%;left:0;opacity:0;overflow:hidden;position:absolute;top:0;transition:opacity 200ms;width:100%;"><img src="https://fast.wistia.com/embed/medias/d4c8hwxm4h/swatch" style="filter:blur(5px);height:100%;object-fit:contain;width:100%;" alt="" onload="this.parentNode.style.opacity=1;" /></div></div></div></div>`

...the problem will occur when you add Free Attachments (and probably other types of resources) to an existing Document.

**Comment by daviddurand** [comment]
So this is happening when the Tizra admin uses multipart posting, rather than form-encoding, and the content contains javascript, and the response page runs any javascript. This generally happens whenever an attachment is uploaded, and whenever there are more than a certain number of form fields (including the many hidden ones).

There are headers we can set to turn off and/or limit these checks, and that's what we will do. It may take a little time to find the best settings (that make things work without losing any security benefits the checker does offer).

**Comment by daviddurand** [comment]
**closing ancient/fixed bugs**
