### ISSUE TITLE
Unpublish Doesn't Work from Lists

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#460]
When I try to unpublish items by checking them off on a list then clicking Unpublish nothing happens.  Delete and Publish operations seem to be OK.

Tested on Collections, Documents, Excerpts and Static Pages.

**Comment by agriffis** [comment]
I've seen this too, reported in #452

**Comment by adane** [comment]
Thanks, Aron!  I labeled this one as duplicate.  Is it proper protocol to close it also?
