### ISSUE TITLE
Insert space between words on labels for Edit User Account Information form

### ISSUE THREAD

**Issue by JessicaSchouten** [Tizra/Tizra-Customer-Tracker#467]
HTML labels (and placeholders) for first name and last name have no space between the words, appearing as "FirstName" and "LastName". 

While I _could_ work around this, it seems like a very quick change might negate the need for customers to manipulate the text or rebuild the form.

As seen on an edited Quickstart 2.6.2:
![image](https://user-images.githubusercontent.com/48992376/60891811-a65a4680-a223-11e9-8b60-a511acd7d9b3.png)

**Comment by daviddurand** [comment]
This is just a question of the "Display name" of the user properties in question. If you pop up the property definition editor in the user list, you can change the string displayed in the labels.
<img width="1450" alt="Screenshot 2019-07-09 13 06 08" src="https://user-images.githubusercontent.com/1316941/60908821-c6e9c700-a24a-11e9-8991-7840a7f53850.png">


Making the change there should do the trick, and will also take effect immediately.
