### ISSUE TITLE
Offer Creation Results in Errors

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#479]
Clicking "Create Offer" on Document and Collection Properties screens results in the following error...

`Template error on operation createForm The following has evaluated to null or missing: ==> operationObject.hasPricingFormula [in template "com/cubchicken/admin/metaTypes/offer/form_edit.ftl" at line 151, column 30] ---- Tip: It's the step after the last dot that caused this error, not those before it. ---- Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)?? ---- ---- FTL stack trace ("~" means nesting-related): - Failed at: #if operationObject.hasPricingFormula() [in template "com/cubchicken/admin/metaTypes/offer/form_edit.ftl" at line 151, column 25] - Reached through: #include "/com/cubchicken/admin/metaT... [in template "com/cubchicken/admin/metaTypes/offer/createForm.ftl" at line 17, column 5] ~ Reached through: #nested [in template "com/cubchicken/admin/adminCommonMacros.ftl" in macro "ajaxableResult" at line 83, column 1] ~ Reached through: @admin.ajaxableResult section="admin-... [in template "com/cubchicken/admin/metaTypes/offer/createForm.ftl" at line 5, column 1] - Reached through: @(.get_optional_template("/com/cubchi... [in template "com/cubchicken/admin/adminCommonMacros.ftl" in macro "typeTemplateInclude" at line 1960, column 5] - Reached through: @admin.typeTemplateInclude view="${vi... [in template "com/cubchicken/admin/ActionAdminAjaxObject/ajaxresponse_view.ftl" at line 15, column 21] ----`

![image](https://user-images.githubusercontent.com/1355614/167474596-08717f86-4664-44e8-8ab6-0c570eaac1b6.png)

**Comment by daviddurand** [comment]
This is fixed in 2a3516008a09cf50f3ddc5f3055dca84ae030cd5 -- but the patch on the live system was lost in the restart.
