### ISSUE TITLE
SDE Forgot password problem

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#48]
To reproduce:
1. Go to http://handouts.sde.com
2. Make sure you are logged out and click forgot password. 
3. Fill in a username (we were trying with sleblond@hnhsd.org)
4. Click send me a new password

The browser seems to hang while waiting for the server. If the username is not found the appropriate error is shown so seems to be something with sending the mail.

Thanks!

**Comment by daviddurand** [comment]
This may have been my fault, as I'm waiting on the final email server information for SDE, but I started setting it up, so some of the email settings are adjustable for that site now. They should just have had the system default values, but the values were not correct -- wrong (but plausible looking) server name and wrong port (25, but GMAIL uses a custom SMTP port).
