### ISSUE TITLE
Keyword Checklists Are Now Arranged Strangely in the Admin

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#481]
I'm guessing the recent CSS work was behind the funky layout of checkboxes shown in the attached (on the Shiseido site https://s2010432988-admin.tizrapublisher.com/admin/main)

![Tizra_Publisher_for_Shiseido](https://user-images.githubusercontent.com/1355614/197913444-de637efe-6817-4ed8-8ef7-3e61443e077f.png)

**Comment by daviddurand** [comment]
argh... yes, I'll look at it.
