### ISSUE TITLE
General document question..

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#49]
Is it possible to prevent individual documents on a Tizra system from being indexed by search engines?

**Comment by daviddurand** [comment]
yes. In the Site Settings if you set "Control search access at the document level", you can set a flag on each document "allow crawler access".

This has to be set for each document, so it's a bit of a pain, however, if you want most stuff to be searchable.

**Comment by orangedrink** [comment]
Thanks David
