### ISSUE TITLE
Page range problems on iPad

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#50]
We're seeing 404 errors on the iPad when navigating outside the actual page range. For example on a 100 page document the mobile viewer on iPad allows you to go to page 101 and throws the not found error.

It's also possible to navigate to page 0 of a document with the same results. 

We were testing using Safari on an iPad 2

Thank you.

**Comment by daviddurand** [comment]
Thanks... This check from the normal reader got omitted from the iPad reader, and I'd never noticed it. Fixed now.
