### ISSUE TITLE
TRB offer problem

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#54]
I can't figure out why this offer isn't showing up on the TRB site. http://amonline.trb.org/165bcv/
It should be showing on any paywall pages you get to when trying to access a 2011 document. Let me know if you have any questions.

**Comment by daviddurand** [comment]
You had put a filtering tag on offers. The tag is "public". I noticed its presence on the offer that is showing up, and its absence in the offer that was not showing up. Adding it to the new offer and republishing solved the problem.

You may not even want to bother with the admin tag filter in the offer block, as you don't have a lot of offers in play, and my guess is that you can use groups to filter offers that are members-only.

In any case, it wasn't a bug which is nice (for me!).

**Comment by orangedrink** [comment]
Oops. Thanks for the help David!
