### ISSUE TITLE
Rename and Sort Master Blocks

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#57]
This is a lower priority for us, but it has been on my mind for a long time.

It would be nice to be able to rename Master Blocks, and have them sort by alpha order rather than how they are currently. The alpha order would also be helpful when updating a master block. The drop down list seems to be random.

Like I said, this isn't a priority for us, it would be just one of those nice enhancements to the layouts

**Comment by daviddurand** [comment]
The sort will be alphabetical tomorrow.
The update block menu will match that sort tomorrow, but now matches the order in the workench (which is better than random).

Rename will have to wait.

**Comment by ghost** [comment]
Thanks.

Another low priority item would be the Properties page. The order randomizes every time you open that page or save. It would be nice if it was a predictable order as well. Alpha order would work as well for this. Once again, this is a low priority, but could potentially be helpful in terms of production.

**Comment by daviddurand** [comment]
Fixed the sorting of "properties" in layout editor. Will be live tonight.

**Comment by ghost** [comment]
Thanks. Looks great.
