### ISSUE TITLE
Question about Macros

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#58]
Is it possible to nest macros, or have "AND" "OR" statements in the Macro. 
I know it this isn't covered in your crib sheet document, but I wanted to see if it was possible.

For an example, on the paywall page, I have a list of all the access denied macros. 
When the access denied reason is 1, 2 or 3 I want to do a check to see if the content they are trying to access has a specific metadata field (this macro: %IF_CONTEXT_VALUE_BEGIN(METADATA_VALUE:field name,match value)%) so that I can further customize the message for that content. 
Something like this: 
%IF_CONTEXT_VALUE_BEGIN(DENIED_REASON,1)%
    %IF_CONTEXT_VALUE_BEGIN(METADATA_VALUE:contentcategory,seminar)%
        Matchs
    %IF_CONTEXT_VALUE_ELSE%
        Doesn't Match
    %IF_CONTEXT_VALUE_END%
 %IF_CONTEXT_VALUE_END%

**Comment by daviddurand** [comment]
Nesting is very limited -- and there are no booolean combinations of conditions.

You can't nest two kinds of the same macro (like CONTEXT_VALUE_BEGIN) for instance...

This is one of the reasons I want to put a better macro language in place soon...

  -- David

**Comment by ghost** [comment]
Thanks.

Keep me up to date on any progress you make on updating the macro language. The scenario that I included isn't an immediate need, but I do know that eventually this customer would like to add a completely different kind of content. When they do, it would be nice to be able to customize the paywall message based on the content because 1 has seminars that you can register for on their site, and the other would just be content for purchase on our site. For now we will keep things fairly generic.
