### ISSUE TITLE
Error Updating

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#61]
I got the following error message after trying to update the main shell.

Operation failed, error: 
Error encountered
on operation deleteMasterBlockDefinition

After the first time this happened, it now happens when I try to delete a master block, or apply the design to live.
I haven't noticed it anywhere else yet.

**Comment by ghost** [comment]
I'm sorry,  the main shell error was a little different, but now I can't repeat it... Only can cause the delete master block error to show up while trying to delete one.

**Comment by ghost** [comment]
I'm so distracted right now... 

The site this is happening in is http://omniplayground.tizrapublisher.com

**Comment by daviddurand** [comment]
I'm not quite sure what's happening. It sounds like you can't delete a master block, or can't update one.

The first thing to try if there's a problem like this is to reapply a saved layout to the staging site. You'll lose any unsaved changes to staging when you do this, so try to save the current state if you think you are going to lose work.

If the staging area gets corrupted (sometimes multiple users accessing at the same time, or accidental duplicate operations can cause this), it can be rebuilt by loading from a saved layout. You should be able to load from the most recent save, or you might have to go back in time (the latter has not happened in several years, but is theoretically possible).

**Comment by daviddurand** [comment]
Did one of the fixes above work? Is there still an issue here?

**Comment by ghost** [comment]
I'm sorry that i didn't respond. 

I think what was happening was a static page had a custom override, and after removing the override things started to work better.

Thanks for checking.
