### ISSUE TITLE
< Back to My Account -- text and markup

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#62]
Known pages this link is on...
~userOrderHistory
~userInfo

Can we please get it so that this link and "<" are in once piece of markup? 
currently the "Back to My Account" is in an a tag, and the "<" isn't in any markup other than the wrapping div that contains everything else.

I think that including "< Back to My Account" all in a classed, or ID'ed, a href tag would work, or keep them separate but wrap them all in their own div, p, span... whatever.

I would like to make this a button, but I can't get rid of the "<" in the markup.

**Comment by daviddurand** [comment]
added a class `t-arrow-caret` to these

**Comment by ghost** [comment]
Hi David,
Something is off with this markup. I went to look at it this morning on a couple sites and the href isn't showing correctly.
Here is a screen shot. http://screencast.com/t/AjJGEZOs1F

I can't seem to figure out what is causing this problem in the markup, but my guess would be that some markup before the href isn't closed correctly.

**Comment by daviddurand** [comment]
There was a missing quote, now no longer missing.
