### ISSUE TITLE
URGENT!-Problems creating password for SDE users

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#73]
This account is listed as pending in the back end:
mroyal868@yahoo.com

When I fill this in to the username field and click login on the front end I get a 404

I also get an error on that site when I click logout both on the front end and in the admin panel

**Comment by ghost** [comment]
I can't log out from any site I have tested this morning.
Also, the Namic sites username disappeared. I added it back this morning for our customer, but I thought all of this may be connected. http://mgt-namic12.conferencespot.org/

**Comment by daviddurand** [comment]
There are a couple of redirection problems that I'm working right now -- since the URLs are a little different on the live sites (because they are live), some issues showed up that slid by in testing.

I'll have a fix or a regressed version in place soon.

**Comment by daviddurand** [comment]
The redirect problems are fixed, and account claiming and logout are once again working properly.

**Comment by orangedrink** [comment]
OK Thanks David!
