### ISSUE TITLE
URGENT-Any changes made to the AMIA SSO recently?

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#74]
The login buttons point to http://proceedings.amia.org/login/avectra but this page now gives a 404 error. I'm able to see google cached version so it must have been there fairly recently. Any idea why that's missing now?

Here is a screen grab of the page google has cached:
http://screencast.com/t/cW4wPdQhC

Looking at the source of that page it doesn't look like tizra code but the domain is clearly ours. I'm really confused. Was there some kind of redirect that isn't happening anymore? 

They have a conference tomorrow. Please help asap!

Thanks!

**Comment by daviddurand** [comment]
There's definitely something wrong. I'm working a solution, should have it in place shortly.

**Comment by orangedrink** [comment]
AWESOME! Thanks for your quick response!

**Comment by daviddurand** [comment]
By the way, the long link in the body of the page does work, so you might want to put that in the design if you want a quick fix.

The destination of the *"members must _log in_" text is

```
http://my.amia.org/eweb/DynamicPage.aspx?Site=AMIA&WebCode=LoginRequired&URL_success=http%3A%2F%2Fproceedings.amia.org%3A80%2Fauthcallback%2Fu8spg%2Favectra%3Ftarget%3Dhttp%253A%252F%252Fproceedings.amia.org%252F%26authToken%3D%7Btoken%7D
```

And that URL uses the form on the membership site, but it works.

The Amia cookies last a long time, and they persist even after you log out -- that makes testing a bit tricky -- it tends to keep working for a long time after something has gone right, which may be how the problem escaped me.

**Comment by daviddurand** [comment]
By the way, that's the same URL that the one that is broken right now will redirect to. I've got a fix and will put it in place soon.

**Comment by daviddurand** [comment]
It's working again. Thanks for the clear bug report.
