### ISSUE TITLE
URGENT - Error on PDF pages

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#78]
http://screencast.com/t/22XDEN5XwQF

I haven't had time to do much testing but it seems like this is happening on all sites.

Thanks!

**Comment by adane** [comment]
Working on this one right now.  Should be pretty quick.

**Comment by daviddurand** [comment]
It's working now. I made a mistake in an internal upgrade (designed to prevent problems like this).

**Comment by orangedrink** [comment]
OK thanks!
