### ISSUE TITLE
Slow Load of Site Index :: Need Immediate Help

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#79]
Hello David,
We are working on getting this site, http://nfxf.conferencespot.org, launched today but the two indices take about 6 to 8 seconds to load in Chrome. 

Here is one of the indices: http://nfxf.conferencespot.org/pres/

David F added a script to the indices, but I disabled javascript and it still took the same amount of time to load. 
It seems as if the system can load the 225 listings and the associated metadata under 8 seconds, and it also doesn't seem like anything is getting cached in the index because it takes 8 seconds each time i go back to that page. 

Could you please look at the link listed above and helps us figure out how to get this site moving a little quicker? The project manager working on the site needs to get this to the customer today.

Thanks in advanced for you help.

**Comment by daviddurand** [comment]
OK, the new JSon stuff is in place (so you can still see properties from JSon if they are hidden, as long as they are searchable). So you will want to test with the a JSon script that reads the desc property, and when it's ready, you can hide that property and make sure that it's searchable, and the JSon should still work.

**Comment by orangedrink** [comment]
It's working. Thanks David

**Comment by daviddurand** [comment]
I have to say that those abstracts are just popping in, too. 30-60 ms before the reply comes in, and loads in 1ms. Very palatable response. I was worried about delays, but this is quite speedy...
Certainly no interaction penalty, and it's cut page delivery time more than in half, even for that long list.
I've also made a change to template flushing on long lists, which should improve the incremental delivery of these long pages, shortening the time until the user sees the first display of data. Adding the dimension of the logo to the header lets the page display much much quicker on first load.

I'd still really like to see the JSon stuff used in TRB and Amia, where it will make a big difference in the real performance of the site, and also in system load, but I think the new flush changes should make those sites feel a little less ponderous in any case.

**Comment by orangedrink** [comment]
Yeah! I was thinking I would need to show a loading graphic while the abstracts were coming in but no need.
