### ISSUE TITLE
Admin Layout Page - enhancement

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#80]
It can be a bit tedious to backups that are not needed anymore. It would be nice to be able to select multiple backups and delete them similar to file and collection pages.

Not a priority, but I thought it might be something nice to add to the admin area.

Thanks, Ryan

**Comment by daviddurand** [comment]
yes, I agree. I've wanted to get to this for quite a while. There are a number of other things that this page needs as well (like a more usable backup naming and sort order).

When we get around to it, we'll close this bug.

**Comment by ghost** [comment]
Sounds good, thanks... 
I just reread that first sentence, and realized that i forgot the word delete, but you seem to have made sense of it.

Thanks

**Comment by daviddurand** [comment]
This has been fixed.
