### ISSUE TITLE
Excerpts Sometimes Incorrectly Appear in Lists When Filter Is Applied

### ISSUE THREAD

**Issue by adane** [Tizra/Tizra-Customer-Tracker#84]
If you use filtering to reduce the number of Excerpts that appear in the main Excerpt list, and then drill down in the site browser to see the Excerpts within a specific Document, the Excerpt list will show the full list of Excerpts brought up by the filter, regardless of whether those Excerpts are within the Document.

**Comment by daviddurand** [comment]
**closing ancient/fixed bugs**
