### ISSUE TITLE
custom override on page not showing up when published

### ISSUE THREAD

**Issue by ghost** [Tizra/Tizra-Customer-Tracker#87]
A custom override shows up on staging, but not on the live site.

Site: http://kc-lite.omnipress.com

Custom sidebar is on the Presentation index and Index by Track Collections.

It is the same thing added to both. A simple script that allows us to filter the page by some metadata.

It can be found in the masterblock "Sidebar" on those two collections and is classed with "wrap filter".

**Comment by orangedrink** [comment]
Ryan I was able to publish the filters by disaggregating the main shell masterblock. This works for now but eventually we'll want to be sure changes to the main shell will show up on these pages. 

This looks like another case of this bug:
Tizra/Tizra-Customer-Tracker#68

**Comment by ghost** [comment]
Training quirks like this is impossible. This needs to get fixed.

**Comment by adane** [comment]
Ryan--

We're doing the best we can and devoting considerable resources to some very complex requirements that are unique to Omnipress.  As David D. pointed out in some detail a couple of months ago in [this comment](https://github.com/Tizra/Tizra-Customer-Tracker/issues/68#issuecomment-6466505), this limitation has been around for  years and it will be quite difficult to make the changes required to support the particular approach you are trying to take.  There are workarounds available, as outlined.

I know this isn't ideal, and we are open to ideas, but based on our current understanding of the situation, we believe we can provide you and all our customers a better product and service overall by focusing development resource on other issues for now.

Thanks for your understanding.

Abe

**Comment by daviddurand** [comment]
Ryan, I understand your pain on this one, especially since I had a lot of trouble even trying to write an explanation of the problem.

However,  this is one issue, with an unknown _and_ very high cost to fix. There is a workaround, and Omnipress is the only customer to bump into the problem in 5 years. 

I know that nesting master blocks is useful, but I think you can make a scalable reskinnable design with a little extra care about where you put open slots and perhaps a little less liberal nesting.

**Comment by ghost** [comment]
Ok.

**Comment by ghost** [comment]
Just frustrated trying to make the it so that our production team can work on it, but then have to learn about and train system quirks/bugs that won't be fixed. 

I appreciate the explanation, and will try to remember to not ask again for this to be fixed.
