### ISSUE TITLE
No Images coming through in static export

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#89]
In our templates we use images from the site properties area of the admin panel. These should be winding up in the assets folder but it looks like I'm only getting one file in the assets folder. I'm not sure what the file is but it is 0 bytes

http://screencast.com/t/2RsfoDyT 

http://screencast.com/t/cud68hWB

**Comment by daviddurand** [comment]
A lot of the images are missing, and the export is crashing when it tries to read  the nonexistent file. I can get a fix in place, but this is similar to issue #83 which was also related to nonexistent references. Also, you didn't give me the URL, but I'm assuming that that's the site to look at.

**Comment by orangedrink** [comment]
Yes that's the site. omniplayground.tizrapublisher.com
