### ISSUE TITLE
Author names on Author index not separated  (Static Export)

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#93]
For example we have a document where the authors are listed as "Aaron Aardvark;Adam Ant"

But in the Author index our markup is coming out as:
&lt;a href="../../docs/cms.pdf">Aaron AardvarkAdam Ant&lt;/a>

**Comment by daviddurand** [comment]
This was closed along with #94. Both were related to Authors sometimes being lists of values and sometimes simple values.
They should be working now. I see that you are running some tests from the logs!
