### ISSUE TITLE
Alpha Nav in Author index not linking properly (Static Export)

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#94]
As you can see from the screen capture, judging from the first three entries on the AI we should be seeing the letters A, D and R link among others that you can't see in this screen grab.

http://screencast.com/t/pzzwXr5tC

Let me know if you have questions

**Comment by orangedrink** [comment]
I don't think we quite have it yet. See the screen grab

http://screencast.com/t/MxdcTqtC

**Comment by daviddurand** [comment]
I think that one is indexed under "J", isn't it?

We don't list each entry under each author letter. It's possible that we do that online, but it's not so easy on the export, I'm afraid.

**Comment by orangedrink** [comment]
The statement of work is very clear that these indices will "mirror" the online version which does list all appropriate authors under each letter.

If you want to discuss what some other options might be with Steve you could contact him. So far his expectation is that it will function like the online version. We may be able to come to a compromise.

Thank you.

**Comment by daviddurand** [comment]
We're going to try to get this to work the same way on the exported sites.

**Comment by orangedrink** [comment]
Great. Thank you
