### ISSUE TITLE
Static export zip file is 0 bytes.

### ISSUE THREAD

**Issue by orangedrink** [Tizra/Tizra-Customer-Tracker#96]
Good morning. I'm trying to download a copy of the design called "000000-STATIC EXPORT-Design Template 1 - rt sb" from omniplayground as a static export. I'm getting an empty file.

Thanks!

**Comment by daviddurand** [comment]
This seems to have been another consequence of #95, now fixed.

**Comment by orangedrink** [comment]
Thank you David
